### ISSUE TITLE
Make cluster/machinedeployment/appcatalogs CRs namespaced by organization

### ISSUE THREAD

**Issue by corest** [giantswarm/roadmap#103]
## User Story

_As an installation admin I want to make sure that organizations in my installation are isolated in terms of the cluster resources they are using, so that members of one organization only have access to that organization's clusters and their respective custom resources._

## Details

For now all the cluster/machindeployment/appcatalog CRs are deployed in the default namespace.

As we're moving towards providing access to the Management API for customers, it is hard to provide granular access to the CRs in the same namespace.

Some of our customers are using multiple organizations with distinct cloud provider accounts each (a.k.a "BYOC"). Therefore mentioned CRs should be created in respective organization namespaces.

So, for this to work we need:

1. some of the operators to manage organizations namespaces
2. operators working with CRs in respective organization namespace, not a default namespace
3. customer management cluster authorization, bounded to organization namespace role instead of wide scope cluster role.
4. etc ?

## Dependency 

- [x]  #148 Add support for cluster resources namespaced by organization

**Comment by corest** [comment]
> Pretty straightforward. Using watcher with label selector.

That's what I do exactly in rbac-operator to create role/bindings for namespaces

https://github.com/giantswarm/rbac-operator/blob/93e12f0649c31ecb015d0f6ffa6218d28f284021/service/controller/rbac.go#L40-L67

**Comment by yasn77** [comment]
I am not sure if it's related and this is the right place. But Adidas is asking about default apps per org (https://gigantic.slack.com/archives/C6L8J93N0/p1586181458197600?thread_ts=1586176973.194900&cid=C6L8J93N0, https://gigantic.slack.com/archives/C02EVLE9W/p1586177031435300)

This does seem like a useful feature and would be facilitated by this issue.

**Comment by oponder** [comment]
So just to be clear, we're not getting rid of the tenant cluster namespace right?

There are some things that the GS API does that might conflict. Like when installing an app it wants to install it into the tenant cluster namespace. I read that we will keep the tenant cluster namespace, so maybe there is no impact, but just want to confirm.

**Comment by corest** [comment]
Tenant cluster resources go into tenant namespace. We're not changing this

**Comment by corest** [comment]
@JosephSalisbury @snizhana-dynnyk  Do we need separate story for organization operator / crds ? This one doesn't look like it should be in biscuit. We have nothing to do with changing namespaces for clusters/machinedeployments/appcatalogs CRs

**Comment by fiunchinho** [comment]
Are these tenant clusters already created or do we need to deploy a new operator that takes care of that?

After that, IIUC, we need to change the namespace used in our operators, and use the tenant namespace, right?

**Comment by snizhana-dynnyk** [comment]
@fiunchinho this is the spec https://intranet.giantswarm.io/docs/architecture-specs-adrs/specs/namespaced-crs/
 and the [issue](https://github.com/giantswarm/roadmap/issues/148) where `organization-operator` was implemented (manages Organization CRDs).

**Comment by rossf7** [comment]
@corest We were just discussing this in the kickoff for the Metadata for Apps story https://github.com/giantswarm/giantswarm/issues/10930.

We will be creating a new CRD called `appcatalogentry` which we'll make namespace scoped. But we had a question about the appcatalog CRD.

Do you know what the migration process is for converting a cluster scoped CRD to namespace scoped? Can we just define a new API version?

Ping @giantswarm/team-batman 

Admin point. Should this issue be in batman board? At the moment it's only in Celestial and Firecracker.

**Comment by snizhana-dynnyk** [comment]
@rossf7 we do have an issue for migration strategy in WG CP API -  https://github.com/giantswarm/giantswarm/issues/11929 Migration strategy for Organizations, but it is currently not owned by any team. 
We said that whoever starts working on moving CRs to be namespaced by organization should also think about a migration strategy.

And yes, this issue should be in batman as well, sure.

**Comment by rossf7** [comment]
@snizhana-dynnyk Great, thanks for this.  We're going to create the `appcatalogentry` CRD as namespace scoped. We'll use the namespace design already agreed.

When we need to reference an `appcatalog` CR we'll include a namespace field but leave it blank for now.

> In the working group we said that whoever starts working on moving CRs to be namespaced by organization should also think about a migration strategy.

Cool this makes sense. When we're ready to migrate the appcatalog CRD we'll do a time boxed investigation and share the results. Unless another team has already done this.

I've added to Batman board. cc @cokiengchiara

**Comment by anvddriesch** [comment]
I have been brainstorming a little bit on this from the aws-perspective.
Of course we can create CRs in organization namespaces, for example by changing the cluster and nodepool creator in the API. Then, if we want to be able to interact with these resources we also need to change the updater, lister, searcher and so on. Furthermore, for these CRs to be reconciled we will need to change `aws-operator` and `cluster-operator` (and probably others apps as well) because `NamespaceDefault` is hardcoded in there.
This also means that we can not simply create (or migrate) clusters in older release versions to be namespaced by organization. Their operators would not find them anymore. We'd need to maintain the "default" namespace along with the new ones. Upgrading a cluster to the new version would then involve moving it into a new namespace. I am not sure yet which implications that can have. @njuettner  suggested to start by making the namespace configurable and set the default to `NamespaceDefault` first.
The next step is a brainstorming session with more people in it, as this has quite some implications.

**Comment by anvddriesch** [comment]
We had a little session with SIG-operator and team firecracker on this topic today. Quite some important points were raised. Here are the notes I took. Please add points I have forgotten.

- To define a namespace we need one source of truth from which the namespace is propagated. This could be the `cluster` CR.
- From an operator perspective we should try to keep things as open as possible. It would make sense to watch all namespaces and remove all hardcoded namespaces so that the operator can manage resources in any namespace, including the current default one but not limited to it.
- When operators create resources we should create them in the namespace defined by our source of truth CR.
- We also have resources in the cluster namespace - should we keep it like that or change it? It would make sense to have everything related to one cluster in the same namespace. However, this could lead to these resources to suddenly be in the default namespace
- We should be able to upgrade old (nodepool) clusters to the new version with namespace support and in scope of such an upgrade to move to organization namespaces
- We need to make sure that nothing can break on the customer side when we do such a move
- Should upgrade and moving namespaces be the same or separate steps?
- We should not bother with legacy (they can just stay in default namespace) and focus on the new aws release

- When users create CRs they should have the option to create the namespaces explicitly but they should also be able to omit it
- We need sane defaults. These defaults could  be just the default namespace, or the organization the cluster is created from (We can then add more fine-grained namespace definitions for users)
- not everything has to be in a namespace (other than default) and resources in older versions won't be. We need to account for that
- We should think about things like two orgs being able to access one cluster

ping @puja108

**Comment by fiunchinho** [comment]
It feels like we are mixing/coupling two different issues: CR placement and access control. Can we give to a user access to a set of namespaces (like namespaces that contain certain label)? Or it necessarily needs to be "one user can access only one namespace"? If we can, we can decouple those two issues from one another. We could have namespaces for clusters (like we currently do for apps stuff), but also organization namespaces to store other CRs.

**Comment by marians** [comment]
@fiunchinho Since namespaces are commonly used in k8s to give permissions to certain resources in these namespaces, I think it is hard to separate the two issues form each other. Putting everything that belongs to a tenant cluster in the same namespace will likely be one of those sane defaults (with alternatives) that we will need in order to have a simple enough product for the majority of users.

**Comment by fiunchinho** [comment]
That would mean changing how apps manage all their stuff I guess, since they use the "namespace per cluster" approach.

**Comment by snizhana-dynnyk** [comment]
@cokiengchiara @rossf7 are you planning to migrate Appcatalog CRD to be organization scoped? If you have an issue for this, could you please add it to WG CP API for tracking? Thanks!

**Comment by rossf7** [comment]
>  are you planning to migrate Appcatalog CRD to be organization scoped?

@snizhana-dynnyk We want to do this but I think its still a way off. But creating an issue to track it makes sense to me. @cokiengchiara WDYT?

**Comment by cokiengchiara** [comment]
> > are you planning to migrate Appcatalog CRD to be organization scoped?
> 
> @snizhana-dynnyk We want to do this but I think its still a way off. But creating an issue to track it makes sense to me. @cokiengchiara WDYT?

Here you go https://github.com/giantswarm/roadmap/issues/219 let's see in planning when we could prioritize this

**Comment by cornelius-keller** [comment]
This is waiting for certificates generated in the organization name spaces. @giantswarm/team-ludacris. Moving it back to backlog for now.

**Comment by JosephSalisbury** [comment]
Does anyone have a veto on not doing this for the pre-CAPI platform? 

Batman still needs to migrate App Catalog CRs, have a separate issue (https://github.com/giantswarm/roadmap/issues/219), this issue is only for cluster resources

**Comment by snizhana-dynnyk** [comment]
@cokiengchiara this is done for Azure and AWS. Is there still work for Batman or do you track it separately? In this case I would close this issue.

**Comment by anvddriesch** [comment]
It is _possible_ in AWS but as of right now new clusters are still created in the default namespace if we go the kubectl-gs/happa route.

**Comment by snizhana-dynnyk** [comment]
from WG MAPI sync - we need to align this across providers and create cluster resources in org namespaces by default.
According to @alex-dabija, there is no need for a new release to change this in the admission controller.

**Comment by rossf7** [comment]
> this is done for Azure and AWS. Is there still work for Batman or do you track it separately? In this case I would close this issue.

@snizhana-dynnyk @cokiengchiara Catalog CRD changes are done and were deployed earlier for https://github.com/giantswarm/roadmap/issues/219

We still need to create public docs but that is tracked separately in https://github.com/giantswarm/roadmap/issues/291 so I think we're done from a batman POV

**Comment by snizhana-dynnyk** [comment]
TODOs for Firecracker:

- [ ] make a change in admission controller to create cluster resources in org namespaces by default
- [ ] update docs with a release version where org namespace is used by default https://docs.giantswarm.io/general/organizations/#namespace-use
- [ ] close this issue 🎉

cc @alex-dabija

**Comment by snizhana-dynnyk** [comment]
wow we can close this one 🎉
