### ISSUE TITLE
kubectl-gs login should allow working with arbitrary context names

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1082]
## User story

- As a cluster admin, I want to use `kubectl gs login` to create workload cluster certificates, using a kubeconfig file I have manually created with context names that I have chosen/created to match my purposes.

## Background

Currently it is not possible to use `kubectl gs login` with arbitrary context names. All these methods fail for different reasons:

1. `kubectl gs login INSTALLATION`: Here a context named `gs-INSTALLATION` is searched for, and if not found, the command exits.
2. `kubectl gs login URL`: Here we try to deduct the endpoint URL and athena URL from the given URL. If that succeeds, we then fetch the installation name from athena and proceed as in (1).

**Comment by marians** [comment]
We should define the rules for when a "gs-" prefixed context is expected. In this case it looks like no problem to remove the check.

**Comment by anvddriesch** [comment]
I see a few implications depending on what we want to support here.

### `kgs login $INSTALLATION`
This one works if a context for the installation in question exists. `kgs` assumes that this context is called `gs-$INSTALLATION` and tries to switch to it. If this should work with other context names we need a different logic to recognize an existing context for an installation, e.g. look for the server address but that is brittle and sounds like a bad idea.

### `kgs login $CONTEXT`
This one currently works the same way as above, first checking for the `gs-` prefix and then trying to switch to the existing context. (In fact it calls the same function as the above command after the check)
However, we could remove the check and let this accept any context name. The problem we'd need to sort out here though would be to define what is a context name and what is an installation name so that the above still works if we remove the check.

### `kgs login $URL`
This one is going to use the provided URL to login and the resulting context is called `gs-$INSTALLATION` by default. We could add a flag to override this with an arbitrary context name.
The danger here would be that it will be easier to create two contexts for the same cluster which is not supported by dex and will result in a "token already claimed by another client' error when trying to use the existing context after the new one has been created.
