### ISSUE TITLE
Spec for Admin users to inspect other users/groups permissions

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1085]
Towards #808 , specifically https://github.com/giantswarm/roadmap/issues/1086

Create a UI spec for this story:

> As an admin, I want to see which permissions a user or group member will have when accessing the Management API, so that I can tweak the permissions if needed.

**Comment by marians** [comment]
First UI spec available in https://www.figma.com/file/37ictqqs7NhwYBuRwsDhP4/Happa-permissions-inspector?node-id=0%3A1

Default state `Myself`:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/273727/167823025-a1074648-820b-4a85-b9a9-c1eb2730fee7.png">

User selected `Group`:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/273727/167823114-9f29db67-0670-439e-9765-d62cb7247fab.png">

User selected `User`:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/273727/167823154-755f7a8d-8996-45ee-bbe0-006b6e25bc44.png">

### Behaviour

- When switching the radio buttons, we want to prevent showing permissions in tabs section (Global, Organizations) that do not fit the selection above.  E. g. switching from `Myself` to `Group` should result in the tabs content either be removed or displayed in a way that appears as "invalid" (e. g. dimmed, blurred, overlayed). _To be defined_
- When changing a user or group name after having clicked `Show permissions`, the same as above should apply.
- Clicking `Shop permissions` will likely require a loading indicator (spinner) to show up.
- When changing the radio buttons, we want to keep the input entered last, and we want to cache the results, so that switching back brings back the permissions inspected before, without requiring new input.
- Load permissions only when clicking `Show permissions`. No action during input.

**Comment by marians** [comment]
The current introduction text includes

> Here you get an overview of your RBAC permissions in the management cluster, with regard to certain use cases.

For admins we should provide a slightly different text. Suggestion:

> Here you get an overview of your own, a group's or a user's RBAC permissions in the management cluster, with regard to certain use cases.

**Comment by marians** [comment]
Done
