### ISSUE TITLE
Use IRSA for `external-dns`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1101]
## Story

_*-As a cluster admin, I want `external-dns` to use IAM Roles for Service Accounts (IRSA) instead of Kiam in order to improve the security and stability of clusters given that Kiam is now deprecated.*_

## Background

Current state:
- Kiam is deprecated and upstream recommends IAM Roles for Service Accounts (IRSA) as the replacement;
- The AWS v17.1.0 release introduced IAM Roles for Service Accounts (IRSA) support;
- Giant Swarm is going to remove Kiam from the list of default applications;
- `external-dns` is still using Kiam in order to access Route53 to configure DNS;

## Changes

- [ ] configure `external-dns` to use IRSA instead of Kiam;
- [ ] keep the option of switching back to Kiam in case we encounter issues during cluster upgrades;

**Comment by njuettner** [comment]
I spent some time thinking what we need to do in order to make it work.

Main tasks:

- [ ] PR https://github.com/giantswarm/aws-pod-identity-webhook/pull/26 to allow `aws-pod-identity-webhook` injecting IAM role credentials into `kube-system`  
- [ ] PR https://github.com/giantswarm/external-dns-app/pull/168 for external-dns-app 
- [ ] PR for cluster-operator to add cluster-values, unfortunately we need the AWS account ID to make the IRSA annotation work
- [ ] PR for aws-operator to add additional trust-relationship for `CLUSTER_ID-Route53Manager-Role`
