### ISSUE TITLE
add monitoring cloudflared app

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1107]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [ ] ensure it is scraped by Prometheus
- [ ] make sure there are basic alerts

**Comment by glitchcrab** [comment]
cloudflared-app is owned by Cabbage, moving there

**Comment by weatherhog** [comment]
lets find out if anyone is using cloudflared otherwise deprecate the app

**Comment by ced0ps** [comment]
Boerse Stuttgart is using this app.

**Comment by weatherhog** [comment]
@brinker211 any chance that we find out if boerse stuttgart is really using this or if this is just installed?

**Comment by ced0ps** [comment]
For now holding off until we can confirm that this actually is used by customers.

**Comment by ced0ps** [comment]
Spoke to @brinker211 
For now holding off until we can confirm that this actually is used by customers.

**Comment by weatherhog** [comment]
@ced0ps @brinker211 any news on this. Still trying to find out if our cloudflared app is used by customers.

**Comment by ced0ps** [comment]
I checked the installed instances (only Boerse-Stuttgart is using it). They are logging some activity from which I gather it's still in active use.
Since they will be moving away from GS this spring my Vote is to keep it in the catalog until they're gone but not invest in monitoring or updating the app unless the customer gives us a good reason to do so.
@brinker211 and @weatherhog if you :ok: this approach I'll close this ticket.
