### ISSUE TITLE
Verify possibility of using two subnets in a single AZ on AWS

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#1120]
Right now, when creating a WC distributed across 3 AZs on AWS, the "total" CIDR range is divided in 4. 1/4 is assigned to AZ `A`, 1/4 to AZ `B`, 1/4 to AZ `C`. The remaining 25% of IPs is lost. This 25% of IPs could greatly help in the case of huge clusters.

It would be interesting to test whether we could "re-use" an AZ twice and assign two subnets to it.

**Comment by paurosello** [comment]
The only viable way nowadays would be to expand the 3rd AZ subnet to use this remaining IP space.

Some thoughts:
- A subnet always has to be divided in even numbers, there is no way to divide it in 3.
- 3rd AZ pod subnet would need to be completely removed and nodes turned off in order to do the change. This is the best option as if we wanted to expand 1 AZ that would mean downtime in all 3 AZs.
- Only this 3rd AZ would benefit from expanded capacity. The cluster could end up being imbalanced as more pods will end up in 3rd AZ.
- Operators would need to be upgraded to provide this feature in a new release as an optional feature. I think we would need to involve manual operations in the clusters to turn off the machines if the customers don't scale down/delete the nodepools beforehand.
- If the customer has Persistent Volume in 3rd AZ they might face some downtime unless it's replicated on the other AZs.

Known limitations:
- AWS CNI does not support adding a second subnet for the same AZ. ENIConfig only allows setting up 1 subnet and here is the upstream issue to add additional subnets but stale for a long time https://github.com/aws/amazon-vpc-cni-k8s/issues/1207

**Comment by othylmann** [comment]
ok, so we are not doing this, ticket closed.
