### ISSUE TITLE
IAM Roles for Service Accounts (IRSA)

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#114]
**Is your feature request related to a problem? Please describe.**

Currently, AWS customers that use the AWS API from the application pods needed to run `kube2iam` or `kiam`. These tools have some inconveniences:

- Modify the node networking layer to catch the AWS API traffic. (It can fail, as example a race condition when the agent Pod was spawned after the application pod. In that case, the iptables rule to intercept the AWS IAM traffic was not installed and the application failed.)
- All workers need to run an agent. (another component taking resources in each worker)
- There is a control plane to configure the pods that use the AWS API. It needs privileges from IAM to manage roles. To be resilient it needs to run in HA.

**Describe the solution you'd like**

Use more native approach as EKS uses for their Kubernetes clusters.
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Describe alternatives you've considered**

Alternatives are the current state, `kiam`.

**Comment by njuettner** [comment]
PoC: https://github.com/giantswarm/giantswarm/issues/14491

Tasks:

- [ ] IAM Roles for Service Accounts Operator
- [ ] aws-operator / k8scloudconfig changes for `kube-apiserver` needs additional flags with OIDC keypair to create `service-account token` and `api-audience sts.amazonaws.com. We need to keep old config otherwise service account tokens which are used before don't work anymore
- [ ] KIAM changes to allow certain calls to the metadata endpoint on each node, e.g. `--whitelist-route-regexp="/latest/meta-data/placement/availability-zone`


Questions:

- Can we store OIDC key as a secret in MC?
- What shall be the name of the S3 bucket for storing JWKS and discovery json? My proposal would be `$clusterid-oidc`?
- What IAM role do we want to use? New IAM role or shall we user the one from aws-operator? What do we need to do in order to update the policy to extend permissions or create a new IAM role?

**Comment by njuettner** [comment]
K8s Secret -> $clusterid-serviceaccount-v2

Flags Naming:

```
- --service-account-key-file=/etc/kubernetes/secrets/service-account-v2.pub
- --service-account-signing-key-file=/etc/kubernetes/secrets/service-account-v2.key
- --service-account-issuer=https://s3-$region.amazonaws.com/awsaccoutid-clusterid-oidc-pod-identiy
```

**Comment by AverageMarcus** [comment]
* [aws-pod-identity-webhook](https://github.com/giantswarm/aws-pod-identity-webhook) chart released as [v0.3.0](https://github.com/giantswarm/aws-pod-identity-webhook/releases/tag/v0.3.0) (to match upstream version) and added to the [default catalog](https://github.com/giantswarm/default-catalog/commit/ed221d7a20837d5ecb1fe0d2f526c0148f27316a)

* KIAM variant chart built as [v2.1.5-irsa](https://github.com/giantswarm/kiam-app/releases/tag/v2.1.5-irsa) and added to the [default catalog](https://github.com/giantswarm/default-catalog/commit/604e3aba9b2e1a22c9357050107e91738863c053)

**Comment by teemow** [comment]
fyi @giantswarm/team-rainbow

**Comment by calvix** [comment]
additional permission we need to add to `aws-operator` role
```
s3:PutObjectAcl
```

**Comment by calvix** [comment]
small progress: manage to put all things together and have it working in the cluster

**Comment by calvix** [comment]
finished the testing, everything seems fine for the alpha version

**Comment by calvix** [comment]
will be part of https://github.com/giantswarm/releases/pull/948

**Comment by calvix** [comment]
docs are avaiable here https://docs.giantswarm.io/advanced/iam-roles-for-service-accounts/
