### ISSUE TITLE
Provision StorageClasses to CAPG clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1204]
## Story

_*-As a cluster admin, I want to have storage classes configured for CAPG clusters in order to run applications which require storage (e.g. Prometheus).*_ 

## Background

Some default applications deployed by default to management clusters require storage. One such application is Prometheus which is required by our monitoring and alterting. By default, there are no storage classes on a brand new CAPG cluster.

**Comment by calvix** [comment]
we should use the CSI app and deploy it together
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver

**Comment by fiunchinho** [comment]
`StorageClasses` are deployed as part of the [gcp-compute-persistent-disk-csi-driver-app](https://github.com/giantswarm/gcp-compute-persistent-disk-csi-driver-app), that [it's a default app](https://github.com/giantswarm/default-apps-gcp/blob/main/helm/default-apps-gcp/values.yaml#L72-L81), so that it's deployed on every gcp cluster.
