### ISSUE TITLE
`coredns` crashes when a custom `serviceCIDR` is used

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1351]
## Task

Propagate the `serviceCIDR` values from the `cluster-gcp/values.yaml` file to the `coredns` app.

## Background

Customers can customize the `serviceCIDR`, but this values is not propagated to the default apps like `coredns`. The `serviceCIDR` values is needed by `coredns` to work as expected. At the moment, it's crashing if a custom `serviceCIDR` is used.

## Outcome

The `serviceCIDR` value from `cluster-gcp/values.yaml` is propagated to the `coredns` app. The app runs without crashing.

**Comment by fiunchinho** [comment]
[The IP used on our `coredns` app](https://github.com/giantswarm/coredns-app/blob/master/helm/coredns-app/values.yaml#L62) needs to be within the `serviceCIDR` configured for that cluster.

**Comment by fiunchinho** [comment]
I have a question. Our `coredns` app is setting the coredns `Service` IP. Even if we propagate the `serviceCIDR` of the cluster to the `coredns` app, what can we do with it? An IP from the CIDR needs to be picked up. I don't think we can do this automatically? Am I miss understanding this?

**Comment by alex-dabija** [comment]
We discussed this during the onsite. We agreed to just pick an IP address from the configured `serviceCIDR` and to assigned it to `coredns`. We do the same on AWS vintage.

**Comment by fiunchinho** [comment]
I made a new release of `cluster-apps-operator` that creates the `cluster-values` configmap with the right values.

Now it takes the `serviceCidr` defined in the `KubeadmControlPlane` CR for the cluster being reconciled by `cluster-apps-operator`. Then it picks the 10th IP from that CIDR to be used as the DNS IP. This is [what Kubernetes does too](https://github.com/kubernetes/kubernetes/blob/d436f5d0b7eb87f78eb31c12466e2591c24eef59/cmd/kubeadm/app/constants/constants.go#L653-L668). That means that the `coredns` deployed by `kubeadm` will use the same IP for its k8s `Service` than our `coredns-app` will use. This is important because this IP can't be changed.

The configmap that `cluster-apps-operator` generates contain two important values related to the DNS IP. It sets the DNS IP to be used [by our `coredns-app`](https://github.com/giantswarm/coredns-app/blob/master/helm/coredns-app/values.yaml#L62) as its k8s `Service` IP. But it also sets [the DNS IP for chart-operator](https://github.com/giantswarm/chart-operator/blob/master/helm/chart-operator/values.yaml#L10). 

Apparently, [chart-operator doesn't rely on kubelet configuration](https://github.com/giantswarm/giantswarm/issues/23479) for DNS because it's deployed early in the bootstrap process, even before coredns is deployed, so it needs a custom configuration. I believe this is only required for vintage, but `chart-operator` is used in both vintage and CAPI clusters. I believe in chart-operator we currently set the same DNS IP than we described above for the coredns-app, but we also add the google dns servers. That way, meanwhile the coredns-app is not deployed, chart-operator can resolve DNS.

Anyway, I tested this on `frieza` and it worked. I'm closing it.
