### ISSUE TITLE
CAPG cluster deletion fails because of route not being deleted

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1356]
## Problem

CAPG cluster deletion fails because of route not being deleted.

## Task

Ensure routing rules are deleted in order for CAPG clusters to be cleanly deleted without manual interventation.

**Comment by fiunchinho** [comment]
I tried adding network and subnetwork information to the kubernetes cloud configuration file. I thought that may fix the issue because routes are managed by the controller manager, but after creating a cluster with the new information, this is still happening

```
E0919 11:00:42.535258       1 controller.go:317] controller/gcpcluster "msg"="Reconciler error" "error"="googleapi: Error 400: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE - The network resource 'projects/giantswarm-352614/global/networks/jose88-network' is already being used by 'projects/giantswarm-352614/global/routes/jose88-5af6e514-3ecd-41b1-9ca8-07273fa50452'" "name"="jose88" "namespace"="org-giantswarm" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="GCPCluster"
```

**Comment by fiunchinho** [comment]
Another option to explore: maybe there is a bug in the cloud provider part of the controller-manager, and we need to move away from the in-tree cloud-controller to the out-of-tree cloud controller, at some point, so it may be worth testing if this happens with the out-of-tree cloud-controller. For that we would need to

- create new app to wrap [cloud-provider-gcp](https://github.com/kubernetes/cloud-provider-gcp)
- add new app to [default-apps-gcp](https://github.com/giantswarm/default-apps-gcp)
- change `cluster-gcp` to use `cloud-provider: external` [instead of `gce`](https://github.com/giantswarm/cluster-gcp/blob/main/helm/cluster-gcp/templates/_control_plane.tpl#L98)

**Comment by fiunchinho** [comment]
The `cloud-provider-gcp` component doesn't have docs on how to actually deploy it. There are unanswered questions from the community in both the Github repository and the GCP slack channel on the kubernetes slack. It wouldn't be straight forward to deploy it.

**Comment by fiunchinho** [comment]
I've checked the SDK and there is no parameter to _force_ the deletion of the network. If we would implement an operator to do this, we will get the same error than CAPG is getting.

**Comment by fiunchinho** [comment]
I guess another option would be to create a small operator that watches clusters and once they are deleted, this operator would remove the routes from google cloud. Knowing the name of the cluster , I think it would be easy to filter out which routes need to be removed. What do you think @alex-dabija ?

**Comment by alex-dabija** [comment]
> I guess another option would be to create a small operator that watches clusters and once they are deleted, this operator would remove the routes from google cloud. Knowing the name of the cluster , I think it would be easy to filter out which routes need to be removed. What do you think @alex-dabija ?

@calvix is doing the same now for CAPA. Yes, we can definitely go this route for now.
