### ISSUE TITLE
Update `kubectl gs` to accept various Dex connectors on login

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1592]
With automation for dex configurations we will create more connectors than just `giantswarm` and `customer`.
The first one will be `giantswarm-ad` for azure https://github.com/giantswarm/giantswarm/issues/21627
When using `kgs` we want to be able to select the right connector, even with several being configured or if there are differences between clusters.

**Comment by weatherhog** [comment]
Discussion:
- need to figure out which connectors are configures in kgs
- always have to option to have dex offer all possible providers (only if GS providers are separate - no mix between GS and customer providers)
- could set up 2 different dex instances in MC
- filter the connectors by the endpoint name
- can we customise the dex selection page?

Possible Problems:
- the first selected identity provider will stay selected as the token will refresh. So the selection page wont be shown again unless we use the API URL ( or potentially the flag - which needs to be added ) to call it again
- if we change the template in dex we will change it for all components calling dex, the change will not only be` kubectl gs` specific

AI:
- [ ] check out https://dexidp.io/docs/templates/
- [ ] pair as FE together with václav

**Comment by anvddriesch** [comment]
Note:
We have customers who are running dex instances outside their workload clusters and want to use `kubectl gs` for logging in.
There is a use case for an override flag to select a specific connector.

**Comment by vvondruska** [comment]
A quick look into Dex to see whether it's able to filter connectors or expose them to kubectl-gs revealed the following:
- Dex does not seem to have a way expose the full list of configured connectors via an API endpoint
- It is possible to configure Dex with custom web page templates. The `/auth` page template is aware of the connectors, and could potentially be used to only show the relevant connectors based on user type, however it seems that there is no way to pass the user type to it. It is only aware of the connectors and the current URL path. So unless the path (probably without query string) can be used, we cannot tell the template which connectors to show/hide.
- Dex also allows to pass arbitrary data to the custom templates, however the data can only be static, and it is defined in the config map


So in order to present only connectors, which are relevant to the users, we have a few options:
  - Try to use the Path template property to filter the connectors on the /auth page in Dex
  - Implement filtering on the Dex /auth page frontend (JS could check the full URL, determine the type and use it to show/hide or collapse/expand some items in the list)
  - Customize Dex either to expose the list of connectors or to provide more data to the auth template
  - Use another component to choose a connector (e.g. kubectl-gs). Connectors would still need to be exposed to that component by Dex or another service (e.g. Dex authenticator or Athena). The service could read the list of available connectors from Dex's or its own config map.

**Comment by kuosandys** [comment]
From December 7th refinement:
Dex `/auth` page - using JS to filter connectors from query parameters:
- sufficient for our use case
  - filter criteria: e.g. `giantswarm` prefix for GS connectors
    -  this is already enforced in `dex-operator`
  - to prevent flickering in the UI: on page load, hide all connectors and only display them after the filtering has been completed
  - if the user does not have JS-enabled, they would just see a list of all connectors
- we would create our own custom dex image, this would also allow us to improve the styling of the UI

kubectl-gs:
- currently we write the whole URL from kubectl-gs using hard-coded connectors
  - we would like to keep this feature so that we can overwrite the connector from kubectl-gs (e.g. from user input via a flag)
  - kubectl-gs is not able to validate the connector, but dex provides a detailed error message if the connector is not valid
  - we could repurpose the `--cluster-admin` flag to specify the filter prefix
- we want to have a flag to re-visit the connector selection page and to refresh the context for the installation (re-login)

Selecting the previously used connector:
- previously selected connector is saved in the user's kubeconfig, so we wouldn't need to re-select the connector
  -  if we really needed the info, we could derive this from the `issuerURL`

**Comment by marians** [comment]
Regarding customer communication:

- A new flag `--connector-id` is introduced. What's the default?
- The previous behaviour is the same as if `--connector-id customer` is used

Documentation changes:

- https://docs.giantswarm.io/use-the-api/management-api/authentication/user/
- https://docs.giantswarm.io/use-the-api/kubectl-gs/login/

**Comment by marians** [comment]
## Possible improvements

### Handle case where no connector matches the filter

<img width="891" alt="image" src="https://user-images.githubusercontent.com/273727/208653834-6eaf3a68-a9c6-4bf9-879a-56086d134154.png">

Possible reasons:

- Giant Swarm staff uses `kubectl-gs login` without flag `--cluster-admin` on a test installation (we don't have `customer*` connectors there)
- User mis-spelled the `--connector-id` value. For this case, it would help to show the value again and show the available connector IDs.
- Configuration does not provide the expected connector(s).

### Show connection ID

Users cannot find out the connector ID to use, unless they have access to the Dex config. We could display the connector ID as additional information in the selection page template to enable users.

### Handle bad connector ID more gracefully

<img width="598" alt="image" src="https://user-images.githubusercontent.com/273727/208654926-08608d72-c49d-4dc1-814b-8003d9e177ab.png">

We can improve this:

- Remove the "Bad request" headline
- Show the connector ID requested in the error message
- Fix spelling
- Show a list of all connectors and their ID?

**Comment by vvondruska** [comment]
PR updating the docs: https://github.com/giantswarm/docs/pull/1666

**Comment by marians** [comment]
We decided to releases this in Januar with appropriate attention and customer communication.
