### ISSUE TITLE
Enable disabling 24/7 support for workload clusters

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#16]
### User story

_- As a Giant Swarm engineer, I want to be able to disable alerting for a CAPI cluster so that I won’t get paged for a testing cluster but still will be able to check monitoring data._

### Description
As a user I'd like to disable the 24/7 support on test clusters. If a customer wants to play with a cluster and try out a service mesh or other things that are currently not officially supported they can turn off our 24/7 support and just play with the cluster. 

The same would work for the SEs. They can disable 24/7 on the clusters that are in an known broken state. 

Additional benefit would be that we start clusters with disable support as a default. This way it would be a conscious decision of the user to turn on the 24/7 support. 

The last point would also allow us to give more partners access to control planes to play with our product. The clusters would all be without 24/7 support and nobody would get paged during the night.

**Comment by JosephSalisbury** [comment]
note to self: bring https://github.com/giantswarm/giantswarm/issues/13990 and https://github.com/giantswarm/giantswarm/issues/13744 in here

**Comment by njuettner** [comment]
I'd like to revive this topic 🙂 . We recently had a request from Adidas to treat all of their clusters in China as production until end of June 2021, which led to an interesting discussion. 

In case we could somehow enable this production true/false toggle, could we also implement some checkers around how we think a production cluster should look like? 
E.g. enabling HA for masters because a production cluster should never run only a single master.

So only in case of meeting all requirements it should be possible to enable "production" mode. 

By default when customer creates a new cluster it should be also treated as "non-production" so customer can only enable it after creation (plus satisfying the contract which we control, e.g. enabling HA) and not directly on cluster creation.

This would also help us improving our on-call situation IMHO.

**Comment by TheoBrigitte** [comment]
This feature was implemented 2yrs ago on 14th Oct 2020 with https://github.com/giantswarm/prometheus-meta-operator/pull/168

And documented recently as part of https://github.com/giantswarm/docs/pull/1632 on Nov 28th and is available at https://docs.giantswarm.io/getting-started/observability/prometheus/disable-monitoring/

**Comment by TheoBrigitte** [comment]
Sorry I missed the `but still will be able to check monitoring data.`

The feature describe previously allow to disabled the entire monitoring stack, meaning to metrics are scrapped.

But we also are able to silence an entire cluster via giantswarm/silence repo. ([example](https://github.com/giantswarm/silences/blob/36e16c82cf56b6077b527e204efe15e036dc3839/otter-csand.yaml))
