### ISSUE TITLE
Migrate `external-dns` to IRSA

### ISSUE THREAD

**Issue by calvix** [giantswarm/roadmap#1640]
## Task

Migrate `external-dns` to IRSA.

## Background

`external-dns` on CAPA still uses Kiam.

## Resources
- [Slack thread](https://gigantic.slack.com/archives/C03LV8E0RL7/p1668582071332699).

**Comment by alex-dabija** [comment]
The `external-dns` app has support for IRSA. It's already running in IRSA mode on vintage. It just needs to be configured to use IRSA.

**Comment by zewolfe** [comment]
Problem
The Cloudfront domain and AWS account ID are needed by external-dns to configure IRSA. This is needed during the cluster creation.
The IAM role needed by `external-dns` also needs to be created on the AWS account in which the cluster resides.

Plan of action:
- [ ] Update the `capa-iam-operator` to reconcile on the `secret` that the `isra-operator` creates. Upon reconciliation it should then create the `route53` role for `external-dns`. This role should have the permissions needed and trust policy as per IRSA [documentation](https://docs.giantswarm.io/advanced/iam-roles-for-service-accounts/#iam-role)
- [ ] Update the external-dns app to update its service account with the ARN of the role created above. See [here.](https://github.com/giantswarm/external-dns-app/blob/master/helm/external-dns-app/templates/serviceaccount.yaml#L6-L8). For this the role name can be derived because we set it above and it'd be a fixed name per cluster. The AWS account ID can be fetched by using this `curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .accountId` called by a unit container if IRSA is enabled

**Comment by alex-dabija** [comment]
Blocked until https://github.com/giantswarm/roadmap/issues/1804 is implemented.
