### ISSUE TITLE
Update CAPA to Kubernetes `v1.23.15`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1669]
## Task

Update CAPA to Kubernetes `v1.23.15`.

## Resources

- [Kubernetes v1.23.15 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#v12315).

**Comment by AndiDog** [comment]
The upgrade to k8s 1.23.15 turns out not so easy:

- Existing cluster has kubeadm config value `imageRepository: k8s.gcr.io` explicitly set in the config map
- CAPI tries to roll out a new node using k8s 1.23.15
- kubeadm 1.23.15 on that node fails to join because the coredns image locations for newer versions have changed (new: `{k8s.gcr.io,registry.k8s.io}/coredns/coredns:the_version`), leading to image pull failures.

This means `golem`, on which I attempted this upgrade, is currently stuck rolling out the new nodes.

From `cluster-api/controlplane/kubeadm/internal/workload_cluster_coredns.go`:

```
// Handle the renaming of the upstream image from "k8s.gcr.io/coredns" to "k8s.gcr.io/coredns/coredns"
toImageName := parsedImage.Name
if (toImageRepository == oldKubernetesImageRepository || toImageRepository == kubernetesImageRepository) &&
	toImageName == oldCoreDNSImageName && targetMajorMinorPatch.GTE(semver.MustParse("1.8.0")) {
	toImageName = coreDNSImageName
}
```

That looks nice and already solved, and is even part of our custom CAPI version, but this image name migration does nothing since we use a custom image repo for CoreDNS (e.g. `image: quay.io/giantswarm/coredns:1.9.3` on `golem`), as it is part of the app platform and not installed via kubeadm.

I had thought this migration would be handled in Kubernetes/kubeadm source code, but it's not. Particularly, it only handles the new registry host 🤬:

```
func GetDNSImage(cfg *kubeadmapi.ClusterConfiguration) string {
	// DNS uses default image repository by default
	dnsImageRepository := cfg.ImageRepository
	// unless an override is specified
	if cfg.DNS.ImageRepository != "" {
		dnsImageRepository = cfg.DNS.ImageRepository
	}
	// Handle the renaming of the official image from "registry.k8s.io/coredns" to "registry.k8s.io/coredns/coredns
	if dnsImageRepository == kubeadmapiv1beta2.DefaultImageRepository {
		dnsImageRepository = fmt.Sprintf("%s/coredns", dnsImageRepository)
	}
```

It also doesn't help that we have `skipPhases: [ ..., addon/coredns ]` (since coredns is an app for us). The `kubeadm join` command will still try to pull them all:

```
// GetControlPlaneImages returns a list of container images kubeadm expects to use on a control plane node
func GetControlPlaneImages(cfg *kubeadmapi.ClusterConfiguration) []string {
	imgs := []string{}

	// start with core kubernetes images
	imgs = append(imgs, GetKubernetesImage(constants.KubeAPIServer, cfg))
	imgs = append(imgs, GetKubernetesImage(constants.KubeControllerManager, cfg))
	imgs = append(imgs, GetKubernetesImage(constants.KubeScheduler, cfg))
	imgs = append(imgs, GetKubernetesImage(constants.KubeProxy, cfg))

	// pause is not available on the ci image repository so use the default image repository.
	imgs = append(imgs, GetPauseImage(cfg))

	// if etcd is not external then add the image as it will be required
	if cfg.Etcd.Local != nil {
		imgs = append(imgs, GetEtcdImage(cfg))
	}

	// Append the appropriate DNS images
	imgs = append(imgs, GetDNSImage(cfg)) // <============ no exception done here

	return imgs
}
```

Some options to try:

- Add migration code for old image repository to kubeadm and wait for another Kubernetes 1.23.x release – 😒⏳
- Work on https://github.com/giantswarm/roadmap/issues/1722 which will anyway override the `imageRepository` setting. If all necessary images are mirrored correctly, that should work. For already-stuck clusters such as `golem`, I may have to cancel the node rotation in order to restart it, unless the rotation has some timeout after which it will retry (quite unlikely to me).
- Immediately, as part of _this_ issue, override `KubeadmControlPlane.spec.kubeadmConfigSpec.clusterConfiguration.dns.imageRepository` to `registry.k8s.io`. The migration code for that repository should work (see above). If that doesn't work, for example because CAPI prefers finishing the cluster upgrade before the config change, we need to find another fix, or cancel the one test cluster `golem` which is stuck and test the upgrade 1.23.13 to 1.23.15 again in another cluster (such as a WC).

**Comment by AndiDog** [comment]
I fixed it in Kubernetes, just because it's the right thing to do (https://github.com/kubernetes/kubernetes/pull/114978). The last release v1.23.15 was on 2022-12-08, so with lots of luck, that fix can get released pretty soon.

Otherwise I'm now following the other ideas.

**Comment by AndiDog** [comment]
I tried changing to `KubeadmControlPlane.spec.kubeadmConfigSpec.clusterConfiguration.dns.imageRepository=registry.k8s.io` on `golem`, but it did not propagate to the existing config map:

```
λ k get KubeadmControlPlane -n org-giantswarm golem -o yaml | grep -A1 dns:
      dns:
        imageRepository: registry.k8s.io

λ k get cm -n kube-system kubeadm-config -o yaml | grep dns:
    dns: {}
```

For the Kubernetes upstream PR, I'm not sure it will go through, based on the comments. If not, we are stuck having a situation where upgrade of all CAPI-managed clusters needs manual intervention to go from < to >= v1.23.15. Unless we find other solutions.

I still see a chance doing this with CAPI alone. The controller applies a changed image repository (but not the special case of a changed DNS image repository); from `cluster-api/controlplane/kubeadm/internal/controllers/upgrade.go`:

```
if kcp.Spec.KubeadmConfigSpec.ClusterConfiguration != nil {
	// We intentionally only parse major/minor/patch so that the subsequent code
	// also already applies to beta versions of new releases.
	parsedVersionTolerant, err := version.ParseMajorMinorPatchTolerant(kcp.Spec.Version)
	if err != nil {
		return ctrl.Result{}, errors.Wrapf(err, "failed to parse kubernetes version %q", kcp.Spec.Version)
	}
	// Get the imageRepository or the correct value if nothing is set and a migration is necessary.
	imageRepository := internal.ImageRepositoryFromClusterConfig(kcp.Spec.KubeadmConfigSpec.ClusterConfiguration, parsedVersionTolerant)

	if err := workloadCluster.UpdateImageRepositoryInKubeadmConfigMap(ctx, imageRepository, parsedVersion); err != nil {
		return ctrl.Result{}, errors.Wrap(err, "failed to update the image repository in the kubeadm config map")
	}
}
```

I will therefore try changing `KubeadmControlPlane.spec.kubeadmConfigSpec.clusterConfiguration.imageRepository` and see if any pending node upgrades then need to be restarted for CAPI to propagate the config.
