### ISSUE TITLE
How should we deal with deprecated schema fields in config

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1750]
See https://github.com/giantswarm/roadmap/issues/1603#event-7954410692

Related: Athena schema: we should remove .kubernetes.caPem (breaking)

**Comment by marians** [comment]
The first thing to do is to add the `"deprecated": true` key to the property, as done here for example: https://github.com/giantswarm/athena/pull/186

In addition, the `$comment` key can be used to add information, e. g. which property is replacing the deprecated one.

Then we need tooling to find out if the deprecated field is still in use in any app config deployed.

If yes, IMO we must assist users/customers in migrating their config. We have to assume the use of GitOps here, where the source is not the resource in the management cluster, but in some other place. That's why communication with customers is important.
