### ISSUE TITLE
Check app-admission-controller reloading certificates

### ISSUE THREAD

**Issue by uvegla** [giantswarm/roadmap#1789]
The `app-admission-controller` is mounting the certificates generated by `cert-manager`. If the pods are running for a long time (it was ~83 days when the issue surfaced) the logs were full of:

```
TLS handshake error from <IP>:<PORT>: remote error: tls: bad certificate
```

and it blocked deploying new apps.

Rolling the deployment solved the issue, so the hunch is that the `app-admission-controller` does not reload the updated certificates. For a regular App that has certs and uses ingress it works because the secret is reloaded by ingress controller when it changes. The `app-admission-controller` might require manual restarts from time to time or we need to solve reloading the cert on change if that really is the root cause.

**Comment by ljakimczuk** [comment]
I think it not a problem with refreshing mounted Secret in the running Pod, I do believe that certificate was successfully refreshed in within the Pod. The problem is the `app-admission-controller` didn't reload them in the memory. It should though, at least in theory, because we use the https://github.com/dyson/certman library for that. It could be a problem with this library, there is an issue for similar issue about re-loading certs in the Kubernetes environment - https://github.com/dyson/certman/issues/2.

I think we could put it into watching for now, and wait for next occurrence to check for the logs indicating problem with re-loading. Then, if we confirm it, we could either contribute to the package to help them push the PR forward, or figure something else. In the meantime we can of course check if there are other, better methods to reload this, maybe other libs.

**Comment by uvegla** [comment]
This happened again for `app-admission-controller` on `puma`. Pods were up for quite some time, like the example above.

**Comment by AverageMarcus** [comment]
We hit this issue again in the test MC for CAPZ (see [Slack thread](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1700122548369699) for details)

In this instance the pods were over 90 days old and was spewing out the same error in the logs. It looks as though the certificate secret was updates 3 days ago (based on the manage fields) which lines up roughly to when we first started seeing the problem with the MC.

After digging in to it some more it looks like the `certman.Watch` doesn't actually have support for watching mounted Kubernetes CM/Secrets due to the way the files are handled by the underlying system.

Details can be found in the following issues in the packages used by `certman`:
* https://github.com/fsnotify/fsnotify/issues/9 (specifically https://github.com/fsnotify/fsnotify/issues/9#issuecomment-679936703)
* https://github.com/fsnotify/fsnotify/issues/292
* https://github.com/fsnotify/fsnotify/issues/300

We'll need to find another solution instead of relying on certman. 😞

**Comment by nce** [comment]
Just [hit this on](https://gigantic.slack.com/archives/C07FE2CTS1K) `puma`

**Comment by weatherhog** [comment]
@uvegla do we still need to do something here as this is happening every now and then?

**Comment by uvegla** [comment]
If we want to fix this, it needs research. At a quick glance it is still not solved upstream or potentially cannot be solved in the dependencies (https://github.com/fsnotify/fsnotify/issues/9). If so, we would need to replace them or implement some hacky mechanism to restart the deployments on intervals.

**Comment by weatherhog** [comment]
please also check https://github.com/giantswarm/roadmap/issues/3709

**Comment by mproffitt** [comment]
Done
