### ISSUE TITLE
Implement dns throttling metrincs in node-exporter

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1811]
Before considering the implementation we will gather metrics about DNS packages lost. Based on that we will decide on further actions.
If dnsmasq is implemented, will have to be included in CAPI as well. Otherwise we can edit node-exporter to include in both if that works out.

Internal thread: https://gigantic.slack.com/archives/C6L8J93N0/p1671439728720789

@tuladhar can you please share your findings here?

**Comment by tuladhar** [comment]
Tested the ethtool collector on grizzly workload cluster, and the metrics is available via node_exporter.

![Screen Shot 2022-12-21 at 6 19 19 PM](https://user-images.githubusercontent.com/5674762/208906218-0e9dbae6-c872-473b-b629-8ff0991cda3b.png)

![Screen Shot 2022-12-21 at 6 16 15 PM](https://user-images.githubusercontent.com/5674762/208905576-cfd614eb-c351-4cdc-b09b-29367e7d983a.png)

Also, tested the following dashboard:
- https://grafana.com/grafana/dashboards/17244-aws-ena-network-performance/?plcmt=footer

![Screen Shot 2022-12-21 at 6 18 28 PM](https://user-images.githubusercontent.com/5674762/208905988-7dd65dba-c7b5-4385-a283-181669b42c8c.png)

![Screen Shot 2022-12-21 at 6 16 32 PM](https://user-images.githubusercontent.com/5674762/208905621-fd0d9f53-a9fa-4333-8b11-e0b145623f50.png)

We need to adjust the dashboard JSON as per our need, such as cluster_id, etc.

**Comment by tuladhar** [comment]
Created PR to enable ethtool collector on node-exporter-app.
- https://github.com/giantswarm/node-exporter-app/pull/164

**Comment by calvix** [comment]
changes in node-exporter changes looks good to me, so lets deploy this further

**Comment by T-Kukawka** [comment]
@tuladhar i know there was an incident on MCs where it was rolled out - do we have a follow up on this?

**Comment by tuladhar** [comment]
Now, that the team is back from Christmas. We need to continue the testing of changes that were done in node-exporter since v1.13.0 which are in master. The last release was done 6 months ago, and lots of changes had been accumulated that caused unexpected issues during rollout. 

We did manage to push one fix in [v1.14.1](https://github.com/giantswarm/node-exporter-app/releases/tag/v1.14.1), but had to be rollback because of prometheus rules failures. [Full thread here.](https://gigantic.slack.com/archives/C01176DKNP4/p1671783652540999)

@T-Kukawka How should we move forward with it, as we need to reproduce the issue again, fixed it and then do rollout once we're confident, that it won't break.

It would be great, If anyone who has worked with node-exporter-app before that can help me on this? As I'm still not familiar with it.

**Comment by T-Kukawka** [comment]
> @T-Kukawka How should we move forward with it, as we need to reproduce the issue again, fixed it and then do rollout once we're confident, that it won't break.

Worth trying WC testing release on our test installations i guess. @njuettner do u have an experience with it?

**Comment by tuladhar** [comment]
Sync'd with Nick, and starting the test release on Gauss installation.

**Comment by tuladhar** [comment]
Along with Erkan, we figured out the major issue with node-exporter between 1.13.0 and 1.14.1:
- In 1.13.0 - node exporter was part of default apps, since beginning.
- In 1.14.1 - node exporter was also pushed to app collection via CircleCI.

Thus, when we release 1.14.1 — we had two copies of node-exporter app running. And because node exporter runs as daemonset and binds to NodePort 10300, we saw pending of pods trying to bind to that port as expected.

Follow up actions:
- [ ] Fix CircleCI config to remove CAPI app collection 
- [ ] Remove node-exporter from CAPI app collection
- [ ] Release the new version of default apps

**Comment by tuladhar** [comment]
Atlas team also found a bug on node-exporter prometheus rule:
- https://github.com/giantswarm/giantswarm/issues/25216

**Comment by tuladhar** [comment]
Deployed v1.14.1 on grizzly, looking good. Now, blocked by Team Atlas to release their prometheus related fixes.

**Comment by tuladhar** [comment]
@T-Kukawka Team Atlas have released v1.15.0, and has been deployed on all MCs. Now the next step would release on customer workload specially on `anteater - peu01`  cluster where we need to gather metrics on DNS throttling.

**Comment by tuladhar** [comment]
Nick working on v18.2.0 release of AWS, with node-exporter v1.15.0, and after that we'll validate on test cluster.

**Comment by tuladhar** [comment]
- [ ] Created workload cluster with AWS release v18.2.0 with node-exporter v1.15.0 on gauss
- [ ] Verified `linklocal_allowance_exceeded` metrics availability
- [ ] Updated [ops-recipes/vpc-dns-throttling](https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/vpc-dns-throttling/) with ethtool collector. [See PR](https://github.com/giantswarm/giantswarm/pull/25384)

Screenshots:
![Image](https://user-images.githubusercontent.com/5674762/213257203-f4f4c025-0fbe-4266-bb47-c02902f6e1f6.png)
![Image](https://user-images.githubusercontent.com/5674762/213257204-e44908c2-9a8b-4343-8f5f-db2914fa3c44.png)

**Comment by T-Kukawka** [comment]
that part is done
