### ISSUE TITLE
keep github connector but automate it with dex-operator

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#1914]
- [x] add github provider to dex-operator
  - [x] check if WC case works via several callback URIs
  - [x] get app
  - [x] get apps age
- [x] alert if needs to be created /renewed
- [x] implement `app-manifest-flow` (related: https://github.com/giantswarm/roadmap/issues/1764 )
- [x] #2197
- [x] allow github group
- [x] https://github.com/giantswarm/giantswarm/issues/26337
- [x] https://github.com/giantswarm/roadmap/issues/2269

**Comment by anvddriesch** [comment]
we tried this out and don't see it being useful to automate github / keep using as idp due to the following limitations
- github api does not support creating and deleting oauth apps
- there is a limit of 100 oauth apps in github and we are almost there

we have been thinking about managing existing configuration with dex-operator until removing github. However, this also doesn't seem to be a good return on effort.
The reason being:
- managing one existing oauth app per one MC would only allow logging into the MC itself (limit of one callback URL, limit of oauth apps as seen above)
- although key rotation would be automated, we would also have to manage the key for dex-operator itself so the ratio of keys to MC would stay the same.

**Comment by anvddriesch** [comment]
I tried out creating a `github app` instead of an `oauth app` and with the right permissions and settings it can be used just the same. (In fact, it's a lot more verbose)
This type of app is also possible to create via the github API https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-github-app-from-a-manifest
For this reason I suggest we migrate to github apps and let them manage by dex operator.

**Comment by weatherhog** [comment]
During refinement we commited on automatic github as dex connector for the future
