### ISSUE TITLE
evaluate device auth for kubectl gs

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1933]
both azure and github offer device auth flow for logging in. This might be faster and enable us to skip opening a browser window when it's not needed. Let's try it out.

**Comment by vvondruska** [comment]
Device auth flow has been implemented as a bash script, which only works on vintage installations atm.
The script is available in kubectl-gs repository, and it can be used by GS staff and customers to obtain client certificates for workload clusters in environments, which do not have a browser or are otherwise restricted.
