### ISSUE TITLE
Ensure DNS resolver rules are attached before the control plane is created

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1950]
## Task

Ensure DNS resolver rules are attached before the control plane is created.

## TODOs
- [x] #2017
- [ ] ...

## Possible solutions
- Use the CAPI pause annotation;
- ...

**Comment by tuladhar** [comment]
### Potential solution 1 - Keep cluster API reconcilation in paused state

Currently, VPC operator unpauses cluster API reconciliation, we can move this unpause logic to resolver operator. AFAIK, for resolver operator only dependency is VPC and IAM. Does that make sense?
> https://github.com/giantswarm/aws-vpc-operator/blob/08684c21a731ce5ac5bf0a46a57bbf81ce0bed22/controllers/awscluster_controller.go#L500-L518

**Comment by alex-dabija** [comment]
> ### Potential solution 1 - Keep cluster API reconcilation in paused state

How do we get around the race condition? We would have 2 different operators which need to signal that the cluster can be unpaused.

**Comment by fiunchinho** [comment]
While working on this I realized something. When I created the `aws-resolver-rules-operator`, I did it following what we usually do, meaning that [it ignores paused clusters](https://github.com/giantswarm/aws-resolver-rules-operator/blob/main/controllers/resolver_rules.go#L95-L98). I did not know that we create clusters with the pause annotation, and only later, it's our `aws-vpc-operator` the one unpausing the cluster. This means that `aws-resolver-rules-operator` was not reconciling our clusters until `aws-vpc-operator` aws done. I thought that maybe we could do it differently, but actually we need to wait anyway for the VPC to be created before we can associate the resolver rules. So I'd say it's fine that `aws-resolver-rules-operator` goes after `aws-vpc-operator`.

**Comment by fiunchinho** [comment]
I pushed an implementation on [this PR](https://github.com/giantswarm/aws-resolver-rules-operator/pull/32). The implementation works as follows.

We create paused CRs when using [the private VPC mode in `cluster-aws`](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/templates/_cluster.tpl#L35-L37). Now we have two reconcilers inside `aws-resolver-rules-operator`. The one it was already there will reconcile paused clusters now. But it will wait until the `AWSCluster` CR has both the `VpcReady` and `SubnetReady` conditions marked as true. This is because we can't associate resolver rules with the workload cluster VPC until the VPC is created. So this reconciler will only associate the rules if those conditions are true. This reconciler only reconciles clusters using the private `dnsMode`.

The new controller inside `aws-resolver-rules-operator` will unpause the CRs when the `VpcReady` and `SubnetReady` conditions are both true. That will unpause clusters using the public `dnsMode` But when using the private `dnsMode` it will require the `ResolverRulesReady` condition to be ready for unpausing the CRs.
