### ISSUE TITLE
Define availability dashboard for Prometheus

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1959]
Towards: https://github.com/giantswarm/roadmap/issues/1956

We need to be able to detect when Prometheus is not meeting the expected availability.
Prometheus is oftenly inaccessible for large cluster (e.g. `anteater / deu01`) which is a sign of degraded service, but we are currently not measuring this.

Let's define some dashboard which can inform us when things are wrong.

Options:
* [nginx ingress success rate](https://github.com/giantswarm/roadmap/issues/1959#issuecomment-1452330761)
* [kube_pod_status_ready](https://github.com/giantswarm/roadmap/issues/1959#issuecomment-1453314075)
* [prometheus_http_requests_total](https://github.com/giantswarm/roadmap/issues/1959#issuecomment-1453315773)
* [blackbox exporter](https://github.com/giantswarm/roadmap/issues/1959#issuecomment-1453318278)

**Comment by QuentinBisson** [comment]
Can we create the dashboard if we do not have https://github.com/giantswarm/roadmap/issues/1964?

**Comment by hervenicol** [comment]
Idea: let's base  ingress error rate.

Pros:
* we already have the metrics, and can already have a quick view in the "nginx ingress controller" dashboard.
* we can see separately prometheus availability (`prometheus-[cluster]` ingress) and agent availability (`prometheus-[cluster]-remote-write` ingress)
* metrics are stored in MC prometheus, meaning we can see them even when the WC prometheus is down.
* we can differentiate broken prometheus from not-existing prometheus: when prometheus is deleted, the ingresses are deleted as well. So errors in ingress mean prometheus exists and is not reachable.

Cons:
* we should artificially create some traffic to have continuous metrics. Because today, no metrics means either prometheus does not exist, or no data is sent.
* there are some cases with prometheus-agent when ingress does not count any requests, for obscure reasons (too many load on the ingress, requests are too large...).

**Comment by QuentinBisson** [comment]
Other idea: We use kube_pod_status_ready to know when the pod is ready.

Or maybe we use both metrics. I don't really like the idea of using nginx metrics because that means the metric rely on 2 components and as you say its flaky

Maybe we could also use those:
```
prometheus_http_requests_total{code="200",handler="/-/healthy"} 16682
prometheus_http_requests_total{code="200",handler="/-/ready"} 16690
prometheus_http_requests_total{code="200",handler="/-/reload"} 4
prometheus_http_requests_total{code="200",handler="/api/v1/label/:name/values"} 5
prometheus_http_requests_total{code="200",handler="/api/v1/query"} 38
prometheus_http_requests_total{code="200",handler="/api/v1/query_range"} 331
prometheus_http_requests_total{code="200",handler="/api/v1/series"} 46
prometheus_http_requests_total{code="200",handler="/favicon.ico"} 6
prometheus_http_requests_total{code="200",handler="/graph"} 4
prometheus_http_requests_total{code="200",handler="/manifest.json"} 2
prometheus_http_requests_total{code="200",handler="/metrics"} 1390
prometheus_http_requests_total{code="200",handler="/static/*filepath"} 12
prometheus_http_requests_total{code="204",handler="/api/v1/write"} 17940
prometheus_http_requests_total{code="302",handler="/"} 1
prometheus_http_requests_total{code="400",handler="/api/v1/write"} 2
prometheus_http_requests_total{code="503",handler="/-/ready"} 2
prometheus_http_requests_total{code="503",handler="/api/v1/query_range"} 2
```

I guess it depends what we want regarding availability :D

For an SLO metric, we would probably go through the ingress but knowing if prometheus is really available could be useful

Even crazier idea, we use the blackbox exporter to check if the ingresses are available? We would not know if the agent is working but we could check that prometheus is ingesting

**Comment by hervenicol** [comment]
Thanks @QuentinBisson, let's split these ideas in different posts for more clarity.

**Comment by hervenicol** [comment]
Idea: Use `kube_pod_status_ready` to know when the pod is ready.

Pros:
* rely on native kubernetes metrics
Cons:
* may not show exactly what the users see, because the whole service availability may depend on other components (like nginx ingress), and healthness probe does not always represent user queries.

**Comment by hervenicol** [comment]
Idea: use `prometheus_http_requests_total`

Pros:
* prometheus-integrated metrics
* shows real error ratio, based on user queries

Cons:
* does not wait for pod to be ready

**Comment by hervenicol** [comment]
Idea: Use the blackbox exporter to check if the ingresses are available

Pros:
* tests the whole access path

Cons:
* We would not know if the agent is working but we could check that prometheus is ingesting
* requires an extra component
* probably requires some extra setup for each new cluster/prometheus (PMO code?)

**Comment by TheoBrigitte** [comment]
We chatted w/ Hervé on Friday:

> Idea: Use the blackbox exporter to check if the ingresses are available

This felt wrong as we would have our availability impacted by ingress availability.

> Idea: use prometheus_http_requests_total

This felt wrong as it does not measure when Prometheus actually responds to queries.

> Idea: Use kube_pod_status_ready to know when the pod is ready.

This felt correct as it actually measure when Prometheus is able to responds to queries.
It might not be perfect as it does not account for actual traffic, but I think we can start with this and improve later on.

WDYT?

**Comment by hervenicol** [comment]
> I think we need to have 2 alerts here.

We're talking about a dashboard here, right?
But yes, we can try to trace both on a dashboard, could be interesting to visualize the differences.

**Comment by hervenicol** [comment]
Work in progress:
![image](https://user-images.githubusercontent.com/12008875/224142335-9c340456-28c2-476a-a07f-d7a6f2f3b793.png)

Not sure whether it should be a separate dashboard or a new row in the main prometheus dashboard.
Suggestions welcome.

**Comment by TheoBrigitte** [comment]
The dashboard seems pretty good, I like the different panels there.

Are all data here are based on `kube_pod_status_ready` metric ?
On the "Prometheus status", bars show downtime for Prometheus right?

I think that's a good start.

**Comment by hervenicol** [comment]
It's all based on `kube_pod_status_ready` here, right. Different ways of looking at the same data :grin: 

The "Prometheus status" graph, on the bottom, shows when each prometheus was running (Ready = Yes) or not (Ready = No). It is quite convenient to know at a given time what was its status, and to spot prometheis that went crazy restarting again and again. We can easily see that k9dw5 and t3yw2 went quite wrong.

The "Prometheus availability per hour" graph on the top shows a more easy-to-read metrics over time.

The "prometheus availability over period" bars, on the left, show the global availability for the selected period.

**Comment by QuentinBisson** [comment]
@hervenicol yes we are talking about the dashboard but the dashboard will also contain the SLI anyway :D And i thought we were in the SLI metric issue :D

**Comment by TheoBrigitte** [comment]
Anything we are missing here?

**Comment by TheoBrigitte** [comment]
Let's no have the nginx data for now. This dashboard is a good first iteration, so we can now see how we perform in term of availability for our Prometheus.
