### ISSUE TITLE
Recreate `grizzly`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2023]
## Task

Recreate `grizzly`.

**Comment by mnitchev** [comment]
We ran into some issues while running `make create-mc`:
1. Irsa operator needs to have the `<cluster-name>-chart-values` configmap created in the kind cluster otherwise it won't reconcile
1. A bug in the deploy-cilium script overwrites the config file instead of appending to it, which breaks the configuration. This leads to the podCIDR and VPC CIDR to overlap
