### ISSUE TITLE
Make upgrade batch size configurable

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#216]
## User Story

As a customer, I want to configure the nodes rolling batch size in order to have less disruptive tenant cluster upgrades.

## Background

33% of nodes are rolled on each upgrade. This is quite disruptive for large clusters with lots of nodes or lots of pods per node because during the upgrade many pods are moved and can put pressure on different components (ex: high load on the image registry).

## Requirements
- must be optional feature defined per tenant cluster in first release (ex: configured via annotation Cluster CR).

**Comment by calvix** [comment]
MaxBatchSize - annotation `aws.giantswarm.io/update-max-batch-size`

here I expect one of two formats
*  a positive integer number to define a number of nodes in a single batch like `2` or `10`, valid values are 0 < x <= instance count
* a decimal number defining a percetange of instances ie `0.3`, valid values in range 0 < y <= 1.0

I want to have validation in the admission controller to inform/block users about using wrong value but I would like to have a safeguard validation in aws-operator as well in case something fails, rather than have crashlooping operator. If the aws-operator sees and invalid value than it would simply use the default one.

annotation would be either on cluster CR or machine deployment CR,  machine deployment value would override any cluster value

@giantswarm/team-firecracker-engineers @giantswarm/sig-ux  please  raise any concerns/suggestion

**Comment by calvix** [comment]
functionality merged into AWS operator and validation in admission-controller, only docs are remaining

**Comment by calvix** [comment]
released as part of https://github.com/giantswarm/releases/pull/512
