### ISSUE TITLE
Machine pool nodes are not drained during upgrade

### ISSUE THREAD

**Issue by bdehri** [giantswarm/roadmap#2170]
## Issue

Machine pool nodes are not drain during a cluster upgrade.

It's probably the root cause for https://github.com/giantswarm/roadmap/issues/1993 .

**Comment by fiunchinho** [comment]
I did a bit of research on the topic. Draining of worker nodes when using `AWSMachinePools` is not currnetly implemented in CAPA. This feature is blocked by this [Graduation of EventBridge Feature](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3414). And [this is the ADR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/docs/adr/0005-graduation%20of%20EventBridge.md) explaining the proposal.

[There was a PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3256) to implement the feature but [it was closed](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3256#issuecomment-1278546479) because of the mentioned "Graduation of EventBridge Feature".

I believe the final implementation would involve deploying this component in our clusters https://github.com/aws/aws-node-termination-handler

**Comment by fiunchinho** [comment]
There is also https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2023

**Comment by fiunchinho** [comment]
There is a k8s built-in mechanism that we could try https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

**Comment by mnitchev** [comment]
Regarding the above `ShutdownGracePeriod`. Kubeadm allows patching the Kubelet config (see [here](https://github.com/kubernetes/kubernetes/pull/110405)) but this was added in 1.25. I'll see if this can be done with a pre/post kubeadm command.
