### ISSUE TITLE
Integrate CAPZ mc-bootstrap tests into current infrastructure

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2220]
Acceptance criteria:

- [ ] CAPZ flow is being tested as part of `/test all-providers` on mc-bootstrap PRs

**Comment by primeroz** [comment]
I will start looking at this 

from https://docs.google.com/document/d/1o6S4XsR_9Uq_1UPcy_pK8Ra5dGKpGAOeUvR5IqgExIE/edit#heading=h.llfrte16vptn 

1. ToDo , need to allocate a cluster name and pre-configure  
    - will use `ghost` subscription with new resourceGroup to avoid having to create a new subscription 
    - capz mc-bootstrap `create-config` target does create some resources in Azure  that **must be protected** from deletion since they are required everytime the `generate-mc` target is called
2. This is already done for CAPZ
3. This needs some attention for CAPZ because the identity used in `kind` and in `azure` are different

**Comment by primeroz** [comment]
this is now merged and working for capz mc-bootstrap
