### ISSUE TITLE
Versioning of IAM permissions in relation to Workload cluster releases 

### ISSUE THREAD

**Issue by luca-rui** [giantswarm/roadmap#2246]
## User Story

- As a customer I want to be able to manage any change to my IAM permissions from a repo, for example [this one](https://github.com/giantswarm/giantswarm-aws-account-prerequisites) and rely on appropriate labels to indicate IAM role version's compatibility to each [Workload cluster releases for AWS](https://github.com/giantswarm/releases/tree/master/aws).
  - The current relation is only stated in form of release notes of the WC release and not easily back-traceable from the IAM repo's perspective.
  - If I want to remove IAM permissions from a certain workload cluster release on, this becomes much more manageable as I'm able to upgrade a cluster and then pull the new IAM permissions
  - Giant Swarm and customers can refer to a common versioning ensuring correct IAM policies

Example: We added more permissions for irsa operator in the [IAM repo](https://github.com/giantswarm/giantswarm-aws-account-prerequisites/pull/45). The related changes came in [release v17.1.0](https://github.com/giantswarm/releases/tree/master/aws/archived/v17.1.0) where we state these IAM requirements only in the release notes of said release. 

## Details, Background

_Please give all possible details, requirements, etc. Technical or not._

## Blocked by / depends on

_Please link issues/epics here which have to be solved before_

**Comment by njuettner** [comment]
I have multiple ideas how we can tackle this and make it easier for customers to figure out which permissions they would need for Vintage releases.

1. We can create a tag for each release, this would mean we're starting by using v19.0.0. Whenever we create a new release, we would tag the IAM repo.

2. We are creating subdirectories for each release for Vintage IAM permissions

Dir structure:
```
vintage / 
  v19.0.0 /
     ...
  v19.1.0 /
     ...
```

3. We can create a branch for each release and reference to the corresponding branch instead of tagging or changing the directory strucuture.

**Comment by njuettner** [comment]
Tagged the current releases > v18.3.0
