### ISSUE TITLE
Define a set of provider-independent workload cluster tests

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2262]
Currently our common tests only [check](https://github.com/giantswarm/cluster-test-suites/blob/main/common/common.go) connectivity to MC and WC so we need to expand them.

Acceptance criteria:
- [ ] Discuss with KAAS CAPI teams what basic provider-independent validation is needed for all of our CAPI WC clusters
- [ ] Translate these requirements to go tests

**Comment by mnitchev** [comment]
I came up with some initial ideas to get the conversation going: 

## Connectivity

- **API** - connect to k8s api
- **Log in the cluster** - This may be a bit tricky as we need to also authenticate to GitHub, but maybe all we need is a token.
- **DNS records** - Check that all dns records are created - `api`, `bastion`, `wildcard` (`ingress` if the app is installed)
- **Prometheus** - Check that prometheus is reachable and make a query. This again might be tricky as it requires login. Also this might be something that atlas needs to help with.

### App platform

- **Make sure all default apps are deployed** - Go over all the Apps for the cluster on the MC and wait for them to become `deployed`
- **Install test app** - Install new test app and check that it's `deployed`. Also go to the WC and check that is' Running. It could be useful to create a dummy app from scratch that can also verify some things on the WC itself for us, but maybe we can figure this out later.
- **Ingress app + connectivity** - Install the nginx-ingress-controller-app and check that we can connect to something. Here the above app may be useful

### Checks inside the cluster

- **Check nodes are up** - should be straight forward
- **Check all pods are Running** - also straight forward
- **ssh** - this may be tricky as we need to set up a key

### Upgrades

- **Upgrade from previous version** - Deploy previous stable version and upgrade to new one (current commit)
- **Rolling nodes** - Could be useful to check if a new node can join the cluster when you've terminated an existing one.
- **Scaling** - Scale up/down the cluster and make sure 
- **Updating the values** - Changing the values is reflected - may be the above is enough here

**Comment by primeroz** [comment]
> Checks inside the cluster

I would like to add CNI status , recently while testing `kube-proxy` replacement for CAPZ i noticed that ( due to an error in the values ) cilium pods would come up and nodes would become READY but cilium was actually crashlooping and CNI was not really working

**Comment by mnitchev** [comment]
That makes sense, but I think it falls into the `Check all pods are Running`, we just need to make sure it's not just Running for a little while before crashing. I've updated the comment.
Does it make sense to try and run `cilium status` on the pods and check that?

**Comment by AndiDog** [comment]
Maybe add a cert-manager based TLS certificate to the nginx-ingress test case, plus checking reachability of `https://ingress`.

**Comment by AverageMarcus** [comment]
> Check nodes are up - should be straight forward

There's currently checks for at least a single control plane node up (and helper functions to assist with that). I think this would be best expanded to be something like "Check number ready nodes matches expected CAPI machines" (or something better worded). This will be easy for control plane as all providers have the same resource for those nodes but when it comes to workers it'll need some way of checking both MachinePools and MachineDeployments.

> Upgrade from previous version - Deploy previous stable version and upgrade to new one (current commit)

I've got a rough example of how to do this in the `clustertest` docs :) 

> Check all pods are Running

Just to be explicit, along with crash looping we should also check for pods stuck `Pending`.

**Comment by whites11** [comment]
In vintage we are using https://github.com/giantswarm/sonobuoy-plugin

Not suggesting to use the same thing, but at least let's reimplement the same feature set

**Comment by njuettner** [comment]
Proposing also to check if PV's are working, creating/modifying/deleting volumes.

**Comment by whites11** [comment]
There are a few tests that we wanted to implement, but struggled for one reason or another:

- During an upgrade, run an external probe towards service exposed by the cluster (ingress) and check number of errors against a defined SLO
- During an upgrade, run an internal probe towards coredns endpoint to ensure DNS resolution works within a defined SLO


Also check https://github.com/giantswarm/giantswarm/issues/23554

**Comment by mnitchev** [comment]
I went over the [sonobuoy-plugin](https://github.com/giantswarm/sonobuoy-plugin) tests and I wrote down what they do:
- [apps_test.go](https://github.com/giantswarm/sonobuoy-plugin/blob/f52796c29811fef781a009d70b8749bd9198d9c8/apps_test.go) - Check if all apps from a release are in the `deployed` state for a cluster. This should map to checking if the `default-apps` are successfully deployed.
- [autoscaler_test.go](https://github.com/giantswarm/sonobuoy-plugin/blob/f52796c29811fef781a009d70b8749bd9198d9c8/autoscaler_test.go) - Create a deployment. Scale it so that it triggers the autoscaler. Check if a node has successfully joined the cluster.
- [cluster_test.go](https://github.com/giantswarm/sonobuoy-plugin/blob/f52796c29811fef781a009d70b8749bd9198d9c8/cluster_test.go) - check the Cluster CR has the expected Spec/Status.
- [cpconnectivity_test.go](https://github.com/giantswarm/sonobuoy-plugin/blob/f52796c29811fef781a009d70b8749bd9198d9c8/cpconnectivity_test.go) - Check connection to API from inside the cluster by deploying a Pod. 
- [ingress_test.go](https://github.com/giantswarm/sonobuoy-plugin/blob/f52796c29811fef781a009d70b8749bd9198d9c8/ingress_test.go) - Deploy nginx ingress app + hello world app that uses it. Check connection to hello world domain from inside the cluster by deploying a Pod. Probably worth checking from outside the cluster too.
- [machinepool_test.go](https://github.com/giantswarm/sonobuoy-plugin/blob/f52796c29811fef781a009d70b8749bd9198d9c8/machinepool_test.go) - get machine pools and check that they have the right amount of instances and are Ready
- [pvc_test.go](https://github.com/giantswarm/sonobuoy-plugin/blob/f52796c29811fef781a009d70b8749bd9198d9c8/pvc_test.go) - deploy a Pod that uses a standard StorageClass PV and check that it becomes Ready

There are some Azure specific ones that I ignored as we're only interested in cross-provider tests. Let me know if I missed anything @whites11
