### ISSUE TITLE
Happa admins logged in via connectors managed by Dex operator cannot manage users

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#2343]

**Comment by anvddriesch** [comment]
Does this block https://github.com/giantswarm/roadmap/issues/2269 ?

**Comment by kuosandys** [comment]
> Does this block #2269 ?

Unfortunately I think it does. User management is done via the REST API and these are the requests that are failing (status code 401). I think we need to update the admin group for `api` - possibly [here](https://github.com/giantswarm/roadmap/issues/2343), though I'm not sure how to accommodate for an array of admin groups.

**Comment by anvddriesch** [comment]
@kuosandys I see. It appears that we define all the groups in the default values [here](https://github.com/giantswarm/config/blob/e0d48c2fe4fba31f848359c5ba4e846546297ab0/default/config.yaml#L9-L14)
My suggestion would be to switch the positions of `giantswarm-ad` and `giantswarm` groups in this configuration. That way azure ad would become the default as it should be which will allow user management as well but we still retain the old group for now until it's removed later.
This would mean that users logged in via `giantswarm-github` can not do this user management which is not so cool but since the rest api is already removed from most places I feel reluctant to change it to work with an array. Also github is supposed to be the fallback option anyway.

**Comment by kuosandys** [comment]
@anvddriesch Sounds good to me 👍 If we're planning to make another announcement once the migration is complete, we could also mention this change.

**Comment by anvddriesch** [comment]
Yeah good idea!

**Comment by kuosandys** [comment]
With the changes above, the requests to `v4/users/` endpoint are now successful when logging in via the `giantswarm-ad` connector.

However, the request to `passage`'s `/invite/` endpoint are failing with status code 500. Example response:
```
{"message":"An unknown error occurred."}
```
The token in the `authorization` header of the request also contains a groups field with the logged in user's groups. We probably need to update `passage` configurations so that it recognizes the Azure AD admin group, though so far I haven't found where that is configured.

**Comment by anvddriesch** [comment]
The problem occurs from [this line](https://github.com/giantswarm/passage/blob/6bcbd128761af252a7c64e2386f7a1a1d4ed6b92/util/jwtutil.py#L34) in passage.
Instead we need to get the `write_all_groups` and `write_all_group` values from config into the passage helm chart and check whether any of those groups are present.

**Comment by vvondruska** [comment]
Mention in the UI that the Giantswarm write all group needs to be used to manage users.
