### ISSUE TITLE
CAPA bastion hosts allow lists

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2349]
## Story

_*-As a cluster admin, I want to have the Kubernetes API protected by allow lists in order to improve the security of clusters.*_

## Background

The bastion host(s) is not protected for public CAPA clusters. This, of course, is really bad for security and needs to be changed.

## Requirements

- Access is restricted by default;
- Firewall rules to allow access only from specific IPs or CIDRs need to be configured for the Kubernetes API and bastions hosts of management clusters and workload clusters;
- Firewall rules must contain the specific port to which access is granted;
- The default list should include Giant Swarm's VPN endpoints;
- The customer needs to be able to configure the list of IPs or CIDRs (values.yml);

## Questions

- Should firewall rules be implemented for private clusters?

## Links

- [capg-firewall-rule-operator](https://github.com/giantswarm/capg-firewall-rule-operator);

**Comment by tuladhar** [comment]
As per Slack discussion with Jose, we will need further discuss on followings:
1. Create dedicated operator for CAPA similar to CAPG
2. Create generic provider agnostic operator.

**Comment by fiunchinho** [comment]
In our CAPA clusters, we configure the SSH server to [listen on a custom port](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/files/etc/ssh/sshd_config_bastion#L17), which the same we try to connect to [when running `opsctl ssh`](https://github.com/giantswarm/opsctl/pull/1534/files#diff-b36ae36252222b889377cfc17b2acddc897132e7cd5f20f3d1a7dba509c842b3R74).

This port is part of the range that it's allowed from everywhere (`0.0.0.0/0`) in CAPA clusters, because CAPA always adds this ingress rule to the worker nodes security group, on all clusters. So we would need to change CAPA to make this ingress rule configurable, similarly to what we are doing for https://github.com/giantswarm/roadmap/issues/2351. Or even, if we change CAPA to allow the customization of worker nodes ingress rules, we could use a completely different port for SSH, instead of reusing the `Node Port Services` ingress rule.

**Comment by fiunchinho** [comment]
It seems that team bigmac is working on Teleport, which will be our solution for SSH / bastion. Their current estimation is for next quarter, so I'd say we could find a solution with teleport, instead of finding a work around for our current solution that will be replaced next quarter anyway.

Shall I move this to blocking until teleport is deployed?

**Comment by fiunchinho** [comment]
@tuladhar is teleport deployed and working on all CAPA MCs? If Puru confirms, we could close this one.

**Comment by tuladhar** [comment]
> @tuladhar is teleport deployed and working on all CAPA MCs? If Puru confirms, we could close this one.

Yes @fiunchinho

**Comment by T-Kukawka** [comment]
Closing in favor of: https://github.com/giantswarm/giantswarm/issues/29254
