### ISSUE TITLE
Upgrade from CAPI v1alpha3/v1alpha4 types to v1beta1

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2350]
[Slack thread #news-dev](https://gigantic.slack.com/archives/C04TGHDEF/p1680523733093799)

CAPI removes v1alpha3 in v1.6 and v1alpha4 in v1.7 (see https://github.com/kubernetes-sigs/cluster-api/issues/8038).

We have at least these references in our code, either direct or via our `apiextensions` repo:

```
λ ag -l --go '".*sigs.k8s.io/cluster-api/.*v1alpha|apiextensions.*(infra|capiexp).*v1alpha' | cut -d / -f 1 | sort | uniq -c | grep -vE '\s(cluster-api|cluster-api-provider-aws)$'
   4 apiextensions
  26 aws-admission-controller
  88 aws-operator
  11 cluster-apps-operator
  31 cluster-operator
   2 core-conversion-webhook
   3 etcd-backup-operator
   2 irsa-operator
  14 kubectl-gs
   7 opsctl
```

**Comment by fiunchinho** [comment]
According to github, those are the GS repositories that depend on CAPI https://github.com/kubernetes-sigs/cluster-api/network/dependents?dependent_type=REPOSITORY&owner=giantswarm&package_id=UGFja2FnZS0yMjY0ODQwNDc2

**Comment by fiunchinho** [comment]
After talking to @alex-dabija we are reducing the scope of the task. The goal of the task is to make sure that all components that are deployed to CAPI MCs are using `v1beta1`. We will ignore components that are deployed to `vintage`. 

On `vintage` we have these versions
```
k get crds clusters.cluster.x-k8s.io -o json | jq '.spec.versions[] | "\(.name)"'
"v1alpha3"
"v1alpha4"
"v1beta1"
```

While on CAPI MCs we will have `v1beta1` and `v1beta2` after the upgrade. This means that we are safe while our components that are deployed to both `vintage` and CAPI use `v1beta1`. 

Eventually, if `v1beta1` is dropped upstream, we may have a problem. But we prefer to only do the work if we need to, rather than do it now.
