### ISSUE TITLE
Simplify `config`, `konfigure`, `collections` and `config-controller`

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2456]
Our current configuration process forces us to use a patched deployment of flux, that has some custom components hooked inside. It makes it almost impossible to use the same flux for customers' needs and makes debugging much harder. We would like to simplify this part.

The currently involved repos are:
- [config](https://github.com/giantswarm/config)
- [konfigure](https://github.com/giantswarm/konfigure)
- collections, like [aws-app-collection](https://github.com/giantswarm/aws-app-collection)
- [config-controller](https://github.com/giantswarm/config-controller/) used only on `vintage` - e.g. for releases - to handle very similar logic to what `konfigure` does.

Current workflow is more or less like this:

```
                                                                               [MCB+CBC repos] or [collections repo pushed to by CI]     
                                                                                   ↓
[config repo] -> {(konfigure plugin for kustomize) -> (kustomize)  -> (flux controllers)} -> [rendered manifests managed by flux]

[ ] - data source
( ) - component
{ } - internal render process inside flux
```

Main comments below from @kubasobon are a short reminder about the components involved in the app configuration process.

We would like to request users of flux, collections and the config repo to leave comments here about the experience you have with this tool set and ides to improve. In particular, please think if:

- Is working with `config`, collections repos and flux is easy? Do you know how to debug it? Do you know how to validate and check the effective configuration without applying it with a real infrastructure?
- If you struggle, then with what? Any ideas about how to improve it?
- If you like some parts or the whole of it, then why?

---
Team internal.

Scope: figure out, plan and execute changes around `config+konfigure` and MCB+CBC repos.

Related to #2457, as it will allow us to run vanilla flux setup, without injecting `konfigure` as a plugin. Might be a blocker for that ticket.

**Comment by pipo02mix** [comment]
> Is working with config, collections repos and flux is easy?

it is not too hard IMO but there are things difficult to visualize when different configuration layers are applied to an app (general defaults vs installation overlay)

> Do you know how to debug it? Do you know how to validate and check the effective configuration without applying it with a real infrastructure?

No I don't, I used konfigure cli but it is not clear if plugin will render the exact same config. Some data is also encrypted so hard to check final result 

> If you struggle, then with what? Any ideas about how to improve it?

In magic land, I wish to have common defaults for the app following the same pattern we use for other stuff (In gitops style) and the use of kustomize to overwrite when it is really needed. Having a tooling that show as final result will be awesome (same we have with fake-flux in GitOps template)

**Comment by piontec** [comment]
We keep some working notes about possible ideas [here](https://hackmd.io/19jp39GRQYGnB2g0s-n6CA)

**Comment by piontec** [comment]
# Decision - accepted idea

## Context

To continue on MCs separation and on the effort to [simplify app-platform and its deployment](https://github.com/giantswarm/roadmap/issues/2454), we need to make sure that the `config` repo is not sharing secrets across MCs of different customers. The second objective is to simplify the deployment of `flux` to just 1 instance per MC.

## Implementation idea

We will include `config+konfigure` in the unified (single deployment) `flux` and split the `config` repo to match the structure of `MCB+CMC` repos.

In this solution, we plan to use our flux distribution (with `konfigure` as `kustomize` plugin) as the only flux installation on an MC (replacing our 2 flux deployments right now). To achieve secrets security, we need to split and migrate the `config` repo similarly as we did with `MCF`. The default part of `config` goes to `MCB`, customer specific part and secrets go to `CMCs`.

### Consequences

- instead of committing configuration info to the `config` repo, our engineers will have to commit it to the same repos we already use for deployment info, so `MCB` and customer specific repos (`CMCs`)
    - it will be now possible to commit deployment and config changes as a single git commit
    - we have to apply the same principle (defaults are public and contain no secrets, overrides and secrets go to customers' repos) to configuration as well
- this change will impact `mc-bootstrap` - needs coordination
- we will be able to run just 1 flux per MC (this will simplify deployment, permissions and help with 2 fluxes hurting each other's performance)

### More implementation details

This requires changes around 3 main components: `mc-bootstrap`, `konfigure` and the `config` repo.

#### mc-bootrstrap

- sync with `tinkerers` about all the important things that have to be applied and influence how `mc-bootstrap` adds config info for new MCs
 
#### Konfigure

- we have to double-check it doesn't kick-in for anything else than `kind: Konfigure` and thus its existence is 100% transparent for customers
- we have to make it join configuration from the `MCB` and the `CMC` repo; this might be achievable by using the flux'es [gitrepo include](https://fluxcd.io/flux/components/source/gitrepositories/#include) feature - we have to check it
- we have to make `konfigure` detect changes in the configuration source and then trigger a reconciliation on flux managed resources

#### Config repo

- we reuse `MCB+CMCs` repos, placing the part of `config` repo in the dedicated folder, like `config/konfigure`; this folder won't be used directly by flux
- we split `config` the same way we did `MCF`: non-secrets defaul configs go to the `config` directory in `MCB`, secrets and customer specific overrides go to the respective `CMC` repo
- we have to plan the migration:
    - make sure the correct (updated) version of `konfigure` is already used
    - detect the secrets present in `config`, ask relevant teams for help with migrating them
    - move configs around
    - reconfigure flux on MCs to use the new config source

**Comment by uvegla** [comment]
# Extension to the above

- Triggering `konfigure` for other resources is not a problem: https://github.com/giantswarm/giantswarm/issues/27597#issuecomment-1632462386
- Instead of Flux `include` feature (which [would work fine](https://github.com/giantswarm/giantswarm/issues/27597#issuecomment-1632522240)) we decided to support 2 new flags in `konfigure` to keep local reproducability:
  - `--dir` flag to be replaced with something like: `--config-defaults-repo` to point to the MCB / default configs
  - `--config-overrides-repo` which can be passed multiple times, order matter, points to CMC repo + taking the already passed installations name we can figure out the folders from the structure (NOTE: this will also tie it to the `gitops-template` structure, OPTIONALLY we can think of making it possible to set exact folders instead of figuring out from the structure assumptions)

**Comment by uvegla** [comment]
@piontec @nce FTR the `config` repo has an `include` folder that supports sharing templates between apps. We need to support that too with the split.

**Comment by uvegla** [comment]
## Extension

Extended issue description: added `config-controller` to the list of components that require a change in order to get rid of the `config` repository.

**Comment by uvegla** [comment]
> > Maybe can be done with an argument that can be passed multiple times or figured out automatically by `konfigure` to check these 3 places for includes (more specific for priority or try to merge?) and ignore if the folder does not exists, fail if the include is not found.
> > WDYT?
> 
> But which component executes that `include` now? Is it `konfigure` itself? If so, then I guess it's enough to keep this structure of `includes` when we split to MCB and CMCs, right?

Yes, it is `konfigure` doing that right now. The point here is to split `config` repo and that comment is about the changes required in `konfigure` and `config-controller` to make it possible. Otherwise I am not sure what you mean by the MCB / CMC split part.

**Comment by uvegla** [comment]
To sum up the necessary changes as I see them now after a long break on this topic:

The `config` repo split would look something like:

- MCB:
  - `config/konfigure/default` contains what is in `config` repo's `default` folder
  - `config/konfigure/include` contains what is in `config` repo's `include` folder
- CMC:
  - `management-clusters/MC_NAME/configs/konfigure` contains what is in `config` repo's `installations/MC_NAME`
  - We might want to support reading `default` and `include` from the CMC repo as well

NOTE: We decided to go this way instead of flux includes so this merge logic is in e.g. `konfigure` itself and thus can be reproduced locally.

Both `konfigure` and `config-controller` needs to do something like:

- new flags/configurations (also must be readable as environment variables) needed, something like:
  - `--config-defaults-repo` (possible can be set multiple times, order matters)
  - `--config-includes-repo` (possible can be set multiple times, order matters)
  - `--config-overrides-repo` (possible can be set multiple times, order matters)

NOTE: We can consider pointing to the folders directly instead of repo roots (the complex one could be the overrides one as it contains the installation name, so it needs to be dynamic).

For `mc-bootstrap` I think these still apply: https://github.com/giantswarm/giantswarm/issues/27629

**Comment by uvegla** [comment]
@giantswarm/team-tinkerers We greatly switched directions on this to minimise the impact and complexity.

The current idea that we are looking into is to:

- Instead of splitting `config` into MCB and CMC repos, we split it like we split MCF to customer config repos, lets call them CCRs (?)
  - The shared parts:`default` and `include` folder go into separate repos too, for example: `config-defaults` and `config-includes` then these are used as git submodules in the CCR repos
    - Feasibility check on submodules with Flux: https://github.com/giantswarm/giantswarm/issues/28415
    - When `config-defaults` and `config-includes` are updated we need a mechanism that automatically bumps forward the submodule on the CCR repos, we are looking into it via: https://github.com/giantswarm/giantswarm/issues/28442
    - Add support for the `include` functionality handling function to be able to load includes from a CCR repo folder in case the customer wants to / makes sense to share their own includes across their configs (our estimation is that this is very simple to do)

What do we win with this approach:

- Greatly reduced complexity, as we do not need to implement the same logic 2 times for `konfigure` and `config-controller`
  - Both components need change but much much less and since the main functionality does not change we need not to fear that the newly generated config differs
    - For example Flux will need to submodule clone for `konfigure`, should be easy + update include function
    - For `config-controller` we need to update the include function and make it clone submodules too
- Rollout should be much more simple, we "just" need to point e.g. `config-controller` to the CCR instead of good old `config` and it will do its thing just the same seamlessly

**Comment by ericgraf** [comment]
@uvegla thank you for the ping. 

What is the reason for creating 3 new repos rather than just creating a subfolder in CMB or CMC and applying an exclude folder path if required? 

One of the current pain points is it is really hard to know where all the configuration exist today and where or how it is getting applied. 
Having to go to 6 different repos to know where to apply something is not easy and drastically increases the confusion when trying to make the correct change. It also makes it hard to know where a config is getting introduced.

A config currently could be applied to any of the following repos.
- CMB 
- CMC
- app-collections
- App repo values files
- config repo
- default-apps

If I got the above correct. I apologize if I didn't. You would be changing this to.
- CMB 
- CMC
- app-collections
- App repo values files
- default-apps
- CCRs
- CD 
- CI 

One final note. If you still choose to add new repos, please change the name of the repos. `CD`  (config-defaults) and `CI` (config-includes) those abbreviations will create constant confusion since they are already a well known abbreviation in the programming community.

**Comment by uvegla** [comment]
@ericgraf Using MCB for defaults and includes + CMCs for customer configs was the original intention but it introduces a lot of issues:

- requires complex changes, but mainly the problem here is that we have to implement it twice: both `konfigure` and `config-controller`. We are more concerned about `config-controller` here
- because of the massive changes it is risky to roll out to legacy clusters and make sure that the configs do not change on them

With the submodule approach we just point the Flux config source and config-controller source to the customer config repos and they pretty much work the same, we only have to do:

- make flux clone submodules and point the source to the respective CCRs
- make `config-controller` clone submodules and point to the respective CCRs

This is significantly safer and lot less effort compared to changing the whole folder structure these config mergers are looking for by convention.
