### ISSUE TITLE
switch flux deployment to single instance

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2457]
Unify our 2 flux deployments in `flux-giantswarm` and `flux-system` into a single one, without giving (yet) full admin permissions to customers. Update our flux release process and monitoring setups.

Blocked by #2456

**Comment by uvegla** [comment]
We agreed to do this after we got rid of `config` repo and `konfigure` because we realised that without that the customer workload would need to be reconciled with the patched `kustomize-controller` with would lead to errors as konfigure needs to have entries for apps in the config repo or worse, it would take configs for customer loads as well from `config` repo. We could patch `konfigure` with some logic to avoid that, but that is one step backward / work spent on going to the wrong direction.

**Comment by uvegla** [comment]
Some things I figure need to be removed to unchain a vanilla, `flux-system` flux:

```shell
k -n flux-giantswarm get deployments | grep controller | cut -d " " -f1 | xargs -I '{}' kubectl scale deployment "{}" --replicas 0

flux -n flux-giantswarm suspend ks flux

# RBAC Operator created stuff

k -n giantswarm scale deployment rbac-operator --replicas 0

rm backup/rb.flux-namespace-reconciler.all.yaml; k get rolebindings -A | grep flux-namespace-reconciler | cut -d " " -f1 | xargs -I "{}" kubectl -n "{}" get rolebinding flux-namespace-reconciler -o yaml >> backup/rb.flux-namespace-reconciler.all.yaml
rm backup/rb.flux-crd-controller.all.yaml; k get rolebindings -A | grep flux-crd-controller | cut -d " " -f1 | xargs -I "{}" kubectl -n "{}" get rolebinding flux-crd-controller -o yaml >> backup/rb.flux-crd-controller.all.yaml

k get rolebindings -A | grep flux-namespace-reconciler | cut -d " " -f1 | xargs -I "{}" kubectl -n "{}" delete rolebinding flux-namespace-reconciler
k get rolebindings -A | grep flux-crd-controller | cut -d " " -f1 | xargs -I "{}" kubectl -n "{}" delete rolebinding flux-crd-controller
```
