### ISSUE TITLE
Certificate management with external CAs and external signers

### ISSUE THREAD

**Issue by vvondruska** [giantswarm/roadmap#2502]
Test a potential solution for certificate management in workload clusters:

- When creating workload clusters, configure CAPI to use kubeadm in external CA mode (i.e. without storing the CA private keys in the secrets and nodes)
- Kubeadm should create CSRs instead of certificates, and have the CSRs approved by a custom component (that we need to write) and certificates should be created from these CSRs and signed by keys retrieved from components running in the management cluster (e.g. by Vault through cert-manager)
- Run Vault in MC to store certificates for WCs

Follow-up of https://github.com/giantswarm/roadmap/issues/2476

**Comment by vvondruska** [comment]
Or maybe there is something I am missing.
@teemow What do you think would be the best way forward?

**Comment by teemow** [comment]
@vvondruska there was a different issue where I've already described all this. We need to use vault the create and seal the roots and we can use cert-manager to rotate the certificates in the clusters with vault as a backend.

**Comment by teemow** [comment]
This comment and the following discussion

https://github.com/giantswarm/giantswarm/issues/15981#issuecomment-1273510880

**Comment by vvondruska** [comment]
@teemow Thanks for pointing me to that issue. I went through it before and the main problem/question that I have at the moment is this:

We can rotate certificates in an existing cluster, but due to CAPI limitations we cannot create a workload cluster with custom certificates. We still need to use the default certificates generated by CAPI and signed either by our CA (which we would need to store as a secret in the MC together with its key) or the default CA created by CAPI.

So, is it OK to create a workload cluster with default CAPI certificates and CA, and replace them with custom certificates signed by an external CA as soon as the cluster is up and running? Or should we look for a different approach?

**Comment by teemow** [comment]
fyi @alex-dabija @puja108

**Comment by teemow** [comment]
Thanks for bearing with me and explaining once more @vvondruska!

So basically for creating a cluster it would be great if 

1) we could pre-create all the certs and give it to the CAPI provider or
2) CABPK (the kubeadm bootstrap provider) would use kubernetes CSRs instead of generating the files themselves. This way we could use cert-manager / vault the same way on the management cluster that we could potentially use on the workload cluster for rotation too.

This is the only thing close that I've found: https://www.youtube.com/watch?v=ItrswNEo5WQ

So instead of generating the CSR files it would be even easier if CABPK would create CSRs in the management cluster API itself. They could be picked up by cert-manager and once the certificates are created the bootstrap starts. 

But I couldn't find anything upstream yet. Can somebody talk to the cluster api people and ask what they would recommend?

**Comment by vvondruska** [comment]
AFAIK we need both. Pre-created certificates are needed to run kubedm init on the control plane nodes. Kubeadm is able to generate CSRs instead of certificates, but only as files stored on the disk, not as Kubernetes resources.
Kubernetes CSR resources are created and used by the worker nodes to obtain certificates to join the cluster.

Maybe it's better to have a call to discuss the details. Manuel set up a call for next week. I will try to summarize and present all the findings, and we can talk about it then.

**Comment by vvondruska** [comment]
The test and underlying investigations were performed with the following conditions and outcomes:

### Objectives:

- Avoid storing private keys of CAs that sign certificates for Kubernetes in the clusters
- Allow customers to provide their own CAs to sign the certificates

### Tested solution

- Use manually managed certificates signed by external CAs
- Store the CAs and their keys in Vault

#### Kubernetes & Kubeadm:

- supports both automatic and manual certificate management
- automatic cert management only works with CA in the cluster/nodes
- manual certificate management works with external CAs
- 2 ways to manually provide certificates to the cluster - both needed
  - pre-signed certificates need to be provided to control plane node(s) before kubeadm init
  - a controller approving and signing csr resources needs to run in the WC to sign certificates for kubelet
- manually managed certificates need to be manually renewed

#### CAPI:

- supports automatic and semi-automatic certificate management
  - automatic = CA and certificates created by CAPI and/or kubeadm
  - semi-automatic = CA(s) provided by the user, certificates created by CAPI and/or kubeadm
- in both cases the CAs and their private keys need to be present in the cluster(s)
  - in the management cluster as secrets
  - on each workload cluster control plane nodes
- manual certificate management and exte5rnal CAs are not supported
- CAs also need to be trusted by CAPI components running in MC to communicate with the WC (e.g. to retrieve status)

#### Workarounds:

- CAPI pre-kubeadm commands
  - pre-signed certificates can be provided to control plane nodes before kubeadm runs
  - after executing the pre-kubeadm commands CAPI creates the CA secret in the MC and overwrites the one from the pre-kubeadm commands
- CAPI post-kubeadm commands
  - WC can be created with default certificates and CAs
  - manual certificates signed by an external CA can be provided to the control plane nodes after kubeadm runs
  - in this case all certificates and CAs need to be rotated and pods/processes running in WC nodes need to be restarted
  
###  Next steps

- Reach out to upstream to find out the following:
  - Is possible to use external CAs and signers with CAPI somehow?
  - If not, is it planned to add support for them to CAPI in the future?
  - Are the external CSR signers (and external CAs) currently used in production anywhere?
- Test a solution with internal CAs in control planes and external CSR signer for kubelets

**Comment by vvondruska** [comment]
Regarding upstream:  
We brought the subject to Cluster API channel in Kubernetes Slack and the outcome is the following:

- A use case very similar to ours (certificates signed with external CAs, using cert-manager and Vault) has already been discussed in the channel
- Using external CAs/providing external certificates to workload cluster nodes is not supported by CAPI at the moment
- Adding support for it to CAPI is not a trivial task. Some work towards is has been proposed (https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210222-kubelet-authentication.md#goals), but it has stalled (as of 4 months ago)
- The other CAPI user who came across this issue soved it by blocking/restricting access to some specific resources like e.g. machine metadata in the cloud provider.

**Comment by gawertm** [comment]
feedback from meeting with @giantswarm/team-shield :
there seems nothing we can do about it now, so we need to go into hardening
when we go into hardening, we should do it in a way that enables easy migration in case upstream CAPI implements the functionalities
near and medium we need to assume customers have access to CP nodes and can schedule workloads there, because thats how its working rn because currently some customers run exporters on the CP nodes and we need to ensure they can scale node pools to 0
but restricted CP nodes are very desirable
short term we need to look into auditing
atlas already has some auditing capabilities, also shield through falco, we gonna investigate this and come up with a auditing solution
idea that only specific processes can access the CA and key files with selinux (in enforce mode). shield will look into this again and come up with a concrete idea how we can restrict something better
shield will also think again if there are more hardening ideas that can be achieved in the short term
