### ISSUE TITLE
Verify CSI Migration Flag Removal

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2536]
### Motivation
With the new V1.25.0 Kubernetes [Promoted core CSI Migration to Stable](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#promoted-core-csi-migration-to-stable). This should not effect us, but we can verify if we can remove the existing CSI Migration Flag. 

### Todo

- [x] verify if we can safely remove the CSI Migration Flag
- [x] Do remove the flag if possible

### Outcome
- We cleaned up the CSI Migration Flag if possible.

**Comment by njuettner** [comment]
In order to mark the migration complete and stopping registering volumes with the in-tree plugin, we should enable the feature-gate `InTreePluginProviderUnregister: true` to kubelet and kube-controller-manager.

```
InTreePluginAWSUnregister: Stops registering the aws-ebs in-tree plugin in kubelet and volume controllers.
InTreePluginAzureDiskUnregister: Stops registering the azuredisk in-tree plugin in kubelet and volume controllers.
InTreePluginAzureFileUnregister: Stops registering the azurefile in-tree plugin in kubelet and volume controllers.
```

Additionally there are still some CSIMigrationProvider flags set in our [source code](https://github.com/search?q=org%3Agiantswarm+CSIMigration+%28language%3AYAML+OR+language%3AGO%29&type=code&l=YAML)

The in-tree plugin will probably removed with an upcoming K8s release:

> We are expecting cloud provider in-tree storage plugins code removal to happen by Kubernetes v1.26 and v1.27. More and more drivers that supports CSI migration will go GA in the upcoming releases.

**Comment by njuettner** [comment]
We have a new dashboard in Grafana (Private Dashboards - Giantswarm / Kubernetes Persistent Volumes)

<img width="2551" alt="image" src="https://github.com/giantswarm/dashboards/assets/1936982/15037f91-fd2e-430d-aa41-7ae7e5d18792">
