### ISSUE TITLE
`app-operator` on `v19` incorrectly trying to modify another clusters ConfigMap

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#2559]
I noticed the following error in the `app-operator` logs for cluster `gorilla / ei9o7`:

```
{
  "caller": "github.com/giantswarm/app-operator/v6/service/watcher/appvalue/cache.go:146",
  "level": "info",
  "message": "failed to add label to `configmap` `rfjh2-cluster-values` in namespace `rfjh2`",
  "stack": {
    "annotation": "configmaps \"rfjh2-cluster-values\" is forbidden: User \"system:serviceaccount:ei9o7:app-operator-ei9o7\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"rfjh2\"",
    "kind": "unknown",
    "stack": [
      {
        "file": "/root/project/service/watcher/appvalue/cache.go",
        "line": 208
      }
    ]
  },
  "time": "2023-06-08T13:00:50.270174+00:00"
}
```

`app-operator` appears to be attempting to add a label to the ConfigMap of another workload cluster, `rfjh2` in this instance, but is correctly being blocked by RBAC.

This is only effecting `v19` clusters and it appears that the ConfigMap that the `app-operator` attempts to modify is the first WC on that MC to have been upgraded to `v19`.

This issue has also been observed on `anteater`.

**Comment by ljakimczuk** [comment]
This is not tied solely to the `v19.0.0` release, for other releases are affected by this as well, for example the App Operator coming from the `v18.4.2` release behaves the same way. See an example from the `apie2` workload cluster in the `anteater` installation:

```text
I 06/13 17:58:06 failed to add label to `configmap` `coredns-user-values` in namespace `seu01` | app-operator/v6/service/watcher/appvalue/cache.go:146
        /root/project/service/watcher/appvalue/cache.go:208
        unknown: configmaps "coredns-user-values" is forbidden: User "system:serviceaccount:apie2:app-operator-apie2" cannot get resource "configmaps" in API group "" in the namespace "seu01"
```

This comes as a result of how we build configs watcher in App Operator, that is we use the version label selector, see [this](https://github.com/giantswarm/app-operator/blob/master/pkg/label/label.go#L20), for watching for App CRs in all namespaces, see [this](https://github.com/giantswarm/app-operator/blob/82531c12094078814174681b362712e71fd6674a/service/watcher/appvalue/cache.go#L30). If there are other workload clusters of the same release version, App Operators of every single one of them will, or rather try to, watch each other's configs.

I'm certain historically it was implemented like this, because until the middle of last year, all App Operators had admin permissions in within the clusters. Then, due to the security incident we had in the middle of last year, we fixed these permissions to be more restrictive. Why the App Operator has stayed configured this way on fixing the incident? I don't know, I remember we surely discussed this, but vaugly remember the outcome of this discussion, my gut feeling is it had to stay this way for some reason and these errors are trade off we agreed to. I will try to look through the issues we had back then and see if I find answer there.

**Comment by ljakimczuk** [comment]
Anyway, I wouldn't be worried about this problem, for these errors come from the cache building part of the App Operator, and as stated yesterday, although I don't recall exactly, I am quite certain it is not an overlook and it had to stay configured this way for a reason. So, the App Operator of one workload cluster does not try to reconcile another workload cluster's apps, it just tries to build cache out of all apps it can see, sometimes including other clusters' apps, what it fails to accomplish for some apps, hence the error, due to insufficient permissions, which is what we actualy want. The error is reported only and it does not harm the processing.

**Comment by kubasobon** [comment]
Pending @ljakimczuk's decision if it's ready to close.

**Comment by kubasobon** [comment]
As per @ljakimczuk, we're safe to close this.
