### ISSUE TITLE
POC: Cilium for everything

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#2560]
As part of the SIG Architecture, we'd like to consider the possibility of collapsing networking features into Cilium.

The general idea is that this would simplify the configuration and operation of these capabilities. We need to find out if that's true and evaluate the maturity of each sub-product.

The features we want to consider are:
- Service Mesh
- Ingress / Gateway API
- API Gateway (?)
- Multicluster connectivity

**Comment by JosephSalisbury** [comment]
me and @mcharriere chatted a bit yesterday

while using cilium to replace multiple components would possible simplify operations for ourselves, we do need to generate some user facing benefits - as some random ideas:

- does request time for a demo application decrease?
- does overall CPU / memory requirements for the networking stack decrease?
- another third thing i can't think of right now

because then we can make a compelling argument for why we're doing the work (to customers), and why customers should upgrade - e.g: you upgrade to the next version, your 99th percentile request time goes down by 50ms

**Comment by ubergesundheit** [comment]
We'll start with investigating Cilium Ingress in ticket #29168

**Comment by kopiczko** [comment]
We had a chat with @mcharriere recently and we both agreed we wouldn't like to bet everything on Cilium anymore.

For Gateway API and and alternative (potentially more performant and reacher in features) ingress we could try Envoy and we don't see benefits of using the Cilium built-in Evnoy.

For Multi-cluster connectivity I don't know. Maybe we should first have a use-case.
