### ISSUE TITLE
Connect Mimir metrics with Grafana cloud

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2565]
In our current setup we are sending data from all our Prometheus MC server to Grafana Cloud.
We want to keep sending those data to Grafana Cloud from Mimir.

There's no remoteWrite support in Mimir, but we might try remoteRead.

**Comment by QuentinBisson** [comment]
This was tried on Gauss using a Prometheus remote reading from mimir and remote writing to grafana cloud.

We need to split the rules like https://github.com/giantswarm/prometheus-rules/pull/790 because rules in a rule group are evaluated sequentially so they take too long with remote read. Due to this, we see a data loss.


The current trial is not taking into account prometheus tsdb series and slos. 

TBD:
- [ ] Finish rule splitting and check Prometheus CPU usage that should increase?
- [ ] Check if we need to have slos and prometheus tsdb series still sent to grafana cloud

**Comment by QuentinBisson** [comment]
I think this is done on Gauss
