### ISSUE TITLE
CSI as default storage solution for AWS workload clusters.

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#264]
CSI as default storage solution for AWS workload clusters.

Customer issue: https://github.com/giantswarm/adidas/issues/519 .

**Comment by njuettner** [comment]
Prepared everything in order to roll this out without breaking things for customers:

There are currently 2 PR's which need to be merged

- aws-operator includes changes for dropping gp2 as the default, this is mainly because gp3 is GA and is set as default in ebs-csi-driver https://github.com/giantswarm/aws-operator/pull/2979. If not specifying the storage class and you would have 2 defaults it will complain. Second part is setting CSI migration flag to true
- k8scloudconfig changes feature flags to set CSI Migration, this will migrate all existing EBS volumes which used the in-tree plugin to use ebs-csi-driver. https://github.com/giantswarm/k8scloudconfig/pull/879

Additionally I added CSI migration complete flag, this will be used in another upcoming release once migration is finished.

Once we draft release v15 we only need to ensure ebs-csi-driver is released automatically.

**Comment by othylmann** [comment]
My little half technical brain is sadly not comprehending :) Are we done? Because we still have this open on the adidas side.

**Comment by njuettner** [comment]
@othylmann 👋🏻  to give you an update. We have it ready for release v15, which we will release soon. Once Adidas is upgrading to that release, they will use CSI as the default for their EBS volumes.

**Comment by teemow** [comment]
@alex-dabija @T-Kukawka this an old issue still labeled with firecracker? To phoenix or close?
