### ISSUE TITLE
Removing `extraOvdcNetworks` doesn't remove them from the vApp.

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#2674]
When removing extraOvdcNetworks, they are removed from the VM but not the vApp.

Context: https://gigantic.slack.com/archives/CE92C4BST/p1689923476691919?thread_ts=1689921019.174329&cid=CE92C4BST

![Image](https://github.com/giantswarm/roadmap/assets/19745768/67e3783e-1292-4226-9688-db8760a23eb0)

**Comment by vxav** [comment]
Ping @erkanerol

**Comment by erkanerol** [comment]
I don't know how we can solve this issue.

Networks are attached to VMs by the machine controller and it only checks a single VCDMachine CR at a time. If the network is not attached to vApp, the controller attaches. Otherwise, cloud director api doesn't allow attaching a network to the vm.

For the update scenario, the controller should check all VCDMachine CRs and ensure there is no VCDMachine CR which has that network in spec. This makes the implementation more complex.

In reality, how frequently will this scenario occur?

**Comment by vxav** [comment]
Hopefully not often. Today I'm going to scale down the capvcd controller, switch off the VAPP and remove the network. If all goes well I think we can leave things like this and add the procedure to the upstream documentation and ours. WDYT?

**Comment by vxav** [comment]
The procedure described above worked fine. I will write something short about it in the README of our CAPVCD app
