### ISSUE TITLE
Investigation - How to wrap Bundles: Bundle Wrapper

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2773]
### Motivation
In https://github.com/giantswarm/roadmap/issues/2523 we learned, that we want to go for a bundle structure with independent lifecycles and minimal possible dependencies between bundles. Now we need to find out, how we wrap those components in bundles and how we manage those bundles, basically what tool to use to create a bundle.

### Todo
- [x] investigate which tool we should use to wrap a bundle
  - as defined in the concept, a bundle should be a list of components and their respective fixed versions. Bundles itself are versioned and hold meta information like their dependency on other bundles, other bundle versions or other bundle version ranges.
  - Checkout if the currently in use App CRs are a potential solution, other alternatives might be Flux Helm Releases, in general solution should work closely with FluxCD - use Flux to our advantage there!
- [ ] document the concept draft or options we have in https://miro.com/app/board/uXjVM0oMunQ=/

### Outcome
- We have a proposal draft (or options) on how to wrap bundles and which tool to use to manage bundles 
(which could also just be the documentation of our current processes)

**Comment by nprokopic** [comment]
When it comes to workload clusters, currently we're deploying apps in two ways:
1. Using Flux `HelmReleases` in `cluster-$provider` apps where we deploy "core" apps such as CSI, CNI, CPI, coredns, and
2. Giant Swarm `App` resources in `default-apps-$provider`, where we deploy a list of apps.

When it comes to bundling and what possibilities we have with aforementioned tools:
1. `HelmReleases` do not have any concept of bundling/grouping of apps, so here we could achieve bundling by simply having multiple `HelmReleases` in a Helm chart (more precisely, multiple `HelmReleases` in a Giant Swarm App). We could use this approach for bundling apps that are currently in `cluster-$provider` apps.
2. Giant Swarm `App` platform already has a concept of bundles, which are implemented as an App of Apps, where one app contains multiple apps inside. One example of this is `observability-bundle`, as well as `default-apps-$provider` which is a bundle itself. We could use this approach for bundling apps that are currently in `default-apps-$provider` apps.

**Comment by nprokopic** [comment]
### How to version example-bundle?

#### Option 1: example-bundle has it's own version and versions of bundled apps are not exposed

Consumers use example-bundle with specific version and they have to update example-bundle to newer version in order to get newer versions of  bundled apps.

Pros:
- Consumers can focus on a bundle as a whole, without the need to dig more into the bundle's details.
- Newer version of the bundle can even add or remove bundled apps, and the consumer just has to update the bundle version.

Cons:
- More steps to get newer versions of bundled apps, as first we have to release new version of the bundled app, change the bundle to use the newer version, release the new bundle version, and then consumers have to update the version of the bundle they use. (Can be automated with automatically merging renovate pull requests.)

#### Option 2: example-bundle has it's own version that is rarely updated (only when the Helm chart "logistics" change), and versions of bundled apps are exposed via Helm values

This way the consumers can set and update the versions of bundled apps by updating Helm values instead of updating the example-bundle.

Pros:
- Less steps to get newer versions of the bundled apps, as the versions of bundled apps are exposed via Helm values, so we have to release new version of the bundled app, and then consumer has to update the bundled app version in Helm values (as the bundle does not specify the version of the bundled app, but it exposes a Helm value to specify the bundled app version).

Cons:
- Bundle is a more lightweight concept here, and bundle consumers have to be more familiar with the bundle internals.
- Consumers have to update their Helm values when the bundle adds or removes bundled apps.

:thinking: Option 1 vs Option 2: It's a tight comparison with two conceptually different options. IMO (Nikola) Option 1 is cleaner and with some dependency update automation it would probably give us overall better, more known and less painfull developer and user experience.

### How can we install the example-bundle?

#### Option 1: installed as a subchart of cluster chart or installed as a subchart of cluster-<provider> app

Pros:
- Helm installs all resources from cluster-<provider> app, cluster chart and the bundle as if they were in a single chart.
- The consumer chart can pass the Helm values to the bundle, so bundle config is visible in a well known place (cluster-<provider> app or cluster chart).

Cons:
- Maybe more steps to update the installed bundle version, as we have to release the new bundle version (or bundled app version), and bundle's version in Helm values in cluster chart, release new version of cluster chart or cluster-<provider> app.

#### Option 2: installed independently from cluster chart and cluster-<provider> app

This would be same approach to how we install default apps today.

Pros:
- Similar to how we install default apps today. (not sure if this is really a pro :) )

Cons:
- Perhaps too decoupled from cluster-<provider> app and cluster chart, e.g. we cannot control order of installation and we rely on eventual consistency (and the past experience shows that cluster deployment can be painfully slow because of that).

:thinking: Option 1 vs Option 2: Option 1 looks better overall so we probably want to go with that one.

**Comment by nprokopic** [comment]
## Bundling apps with Giant Swarm App Platform

Updated [Miro board](https://miro.com/app/board/uXjVM0oMunQ=) with Giant Swarm App Platform approach.

### How to version example-bundle?

Same two options like for HelmReleases.

Option 1 vs Option 2: It's a tight comparison with two conceptually different options. IMO (Nikola) Option 1 is cleaner and with some dependency update automation it would probably give us overall better, more known and less painful developer and user experience. Additionally, we do something similar now with App Platform app bundles (versions of bundled apps are visible in Helm values, but we do not override them from the bundle consumer side and we just use the defaults, so we should maybe just hardcode the versions of bundled apps somehow).

### How can we install the example-bundle?

Same two options like for HelmReleases.

Option 1 vs Option 2: Similarly like for HelmReleases, Option 1 looks better overall so we probably want to go with that one, at least in KaaS, while the platform teams can install their bundles independently on top of cluster apps.
