### ISSUE TITLE
Add `--prevent-deletion` flag to `kubectl gs template cluster` command

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2781]
With https://github.com/giantswarm/roadmap/issues/146 we introduced a mechanism that allows to prevent resources from being accidentally deleted.

If a user wants to apply that mechanism to a cluster the user must apply the label to all resources manually. It would be a good first step in terms of UX if we introduce a flag `--prevent-deletion` to `kubectl gs template cluster` that automatically applies the label to all generated resources.

**Comment by gawertm** [comment]
need to check future of kgs template cluster

**Comment by gawertm** [comment]
for kubectl gs template cluster there is currently no priority. I discussed with product and we can continue to focus on gitops only for now.
There is a plan to introduce a more generic command (kgs create cluster) because we still want to support an imperative way of creating clusters. But that might superseed the kgs template cluster efforts in the end. Honeybadger or turtles will look into this new command and depending on the outcome we will know if we should do something with kgs template cluster or not. In the meantime we can focus on gitops.

**Comment by ssyno** [comment]
When the flag is set to true we will have to add the following so [cluster-cleaner](https://github.com/giantswarm/cluster-cleaner) ingores the cluster:
```
annotations:
  alpha.giantswarm.io/ignore-cluster-deletion: "true"
```

**Comment by gawertm** [comment]
just add a note in the kubectl gs template cluster command that it works for CAPA, CAPA EKS and CAPZ, if not already exist
