### ISSUE TITLE
Add GS EKS based CAPA to the CI pipelines

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2820]
Following Phoenix development on EKS cluster creation based on CAPA, we have created a solution to create the EKS clusters within our current stack on CAPA MCs. The full documentation can be found here: https://intranet.giantswarm.io/docs/dev-and-releng/capi-eks-internal-doc/.

To keep the product up to date and operational we would like to integrate it into our CAPI CI pipelines.

It is CAPA based, however we treat EKS as separate provider with separate apps `cluster-eks` and `default-apps-eks`

**Comment by AverageMarcus** [comment]
As this will be using `grizzly` as the stable-testing MC for EKS WCs there's very little, if anything, needed from Tinkerers side. 

**What's needed:**
* A new `eks` provider directory added under [providers](https://github.com/giantswarm/cluster-test-suites/tree/main/providers) in cluster-test-suites
* Add the `standard` and `upgrade` test suites under the new provider.
* Use the `capa` KubeContext so that it makes use of `grizzly` (with a comment to explain that) or alternatively duplicate the `grizzly` context with the name `eks` in the kubeconfig secret.
* Add the minimum values needed for the cluster and default-apps apps.

_Alternatively:_
The managed WCs could be added as new test suites under the relevant provider directories. E.g. a new `eks_standard` directory could be added below `./providers/capa/`.

Consistency is key so whichever approach is chosen should be the same for all providers. It comes down to grouping by CAPx provider or by `cluster-X` apps.

**Comment by calvix** [comment]
We got pretty far, and almost finished it, but we hit a blocker.  the CI pipelines fetch kubeconfig from a secret named `cluser-kubeconfig` which in normal CAPI cluster has kubeconfig with client cert for auth and that has very long TTL
but for EKS the kubeconfig uses token issues from AWS api and is valid only for few minutes. So we hit a problem where the kubeconfig stops being valid in the middle of the running tests.

**Comment by calvix** [comment]
blocked by expiring kubeconfig, we or tinkerers need to find nice solution

**Comment by T-Kukawka** [comment]
@AverageMarcus i heard u are taking a look here, is that correct?

**Comment by AndiDog** [comment]
If the kubeconfig has a refresh token, we could probably reload the config regularly. In the [Go client](https://github.com/kubernetes-client/go/tree/master/kubernetes/config), I don't see a function to directly refresh, though.

**Comment by AverageMarcus** [comment]
@T-Kukawka We're going to discuss it in the team today.

@AndiDog We use the controller-runtime client (well, we wrap around it). I investigated fetching the latest kubeconfig from the refreshed secret each time here (https://github.com/giantswarm/clustertest/pull/114) but the amount of refactoring that'd need to be done, both in clustertest and cluster-test-suite, would be too much. It would also require all new tests to be wrote with that refresh in mind which wouldn't be clear for those not working on EKS.

**Comment by calvix** [comment]
https://github.com/giantswarm/cluster-eks/pull/41#issuecomment-1812591445

:green_apple: yay
