### ISSUE TITLE
Support CAPI secret name format in kubectl-gs gitops

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2830]

**Comment by piontec** [comment]
In kubectl gs template app when templating an app that will be installed into a CAPI workload cluster it looks like the kubeconfig context name isn't correct.
[This line](https://github.com/giantswarm/kubectl-gs/blob/bb5be37b880daace376be80f5c01c3673d29e01f/pkg/template/app/app.go#L135) generates a context name like t-123456-kubeconfig (where t-123456 is the name of my WC) but in CAPI the context name in the Kubeconfig secret is in the format: t-123456-admin@t-123456.

**Comment by ljakimczuk** [comment]
I've investigated this issue yesterday and came to the conclusion that this field is most probably not used at all, and I am not sure if it has ever been used and if so, how. 

Let's draw the baseline first by checking the right names for contexts in kubeconfigs the App Platform consumes. We have two types, the first coming from the [Cluster Operator](https://github.com/giantswarm/kubeconfig/blob/master/kubeconfig.go#L78), who uses the `giantswarm-CLUSTER_NAME-context` for the context name, and the second coming from the [CAPI Kubeadm Controll Plane Controller Manager](https://github.com/giantswarm/kubeconfig/blob/master/kubeconfig.go#L78) who uses `CLUSTER_NAME-admin@CLUSTER_NAME` for the context name. 

We already know the [KGS](https://github.com/giantswarm/kubectl-gs/blob/bb5be37b880daace376be80f5c01c3673d29e01f/pkg/template/app/app.go#L135) plugin generates the wrong context name for CAPI, by using the `CLUSTER_NAME-kubeconfig`, but apparently this name is also incorrect for the legacy clusters, according to baseline above. Yet, so far no errors have been reported context name-wise, so either KGS is not heavily used, or defaulting is being disabled, in which case App CRs are being templated without context, which is then set by the App Admission Controller. Not encountering this error even once with KGS sounds unlikely though, but I believe it could have slipped our attention for someone else could deal with this by setting the right name for example. Hence I decided to check the App Admission Controller.

Surprisingly, the [App Admission Controller](https://github.com/giantswarm/app-admission-controller/blob/d29dc3601307d9a579990b826cc51cc280a22fc3/pkg/app/mutate_app.go#L248) also uses a wrong name in its mutator, for it is simply the `CLUSTER_NAME`. Interestingly, the App Admission Controller validator does not seem to care for this field at all, there is a check for the kubeconfig Kubernetes Secret existence, but none for the correct context name.

At this point I decided to check other componets that I know have something to do with creating App CRs.

App Bundles, like for example the [Observability Bundle](https://github.com/giantswarm/observability-bundle/blob/df0001efc81da25e6dc592f24843b2bf452f00db/helm/observability-bundle/templates/apps.yaml#L43), seem to use right name for CAPI clusters, the `CLUSTER_NAME-admin@CLUSTER_NAME` , but they also seem to re-use this name for the legacy clusters, for which it is clearly wrong. In other words, bundles seem to simply decide a name regardless the cluster type.

The Cluster Operator creates App CRs itself from configured Release CR, and hence it configures the context name for them. Surprisingly, it does it a wrong way, for the name used is the `CLUSTER_NAME-kubeconfig`, despite the fact that it is in charge of creating cluster kubeconfigs, so it should know what is the right name.

Also in App Platform integration tests we use wrong names. We [create KinD](https://github.com/giantswarm/architect-orb/blob/master/src/commands/integration-test-create-cluster.yaml) cluster with a default `kind-kind` context name in the kubeconfig, yet [App CRs](https://github.com/giantswarm/apptest/blob/86cf1f36d0f77de8e4320934cf9d119358e06ab1/apptest.go#L364) use the wrong `APP_NAME-kubeconfig` names.

The [Cluster Apps Operator](https://github.com/giantswarm/cluster-apps-operator/blob/master/service/controller/key/key.go#L97), when creating Chart Operator, also uses a wrong `CLUSTER_NAME-kubeconfig` context name.

Now, in conclusion, this strongly suggests that this field is not really used, for none of these contexts exists in the kubeconfigs created by the two controller mentioned at the beginning. We could miss errors coming from one component, KGS for example, but since there are more of them, if the context name was of any importance, we would have already realized that. 

To make double sure, I also checked App Operator codebase for any usage of the context name, but could not find any. We use the kubeconfig in the App Operator to get caching clients [here](https://github.com/giantswarm/app-operator/blob/master/service/internal/clientcache/cache.go#L81), but only the Kubernetes Secret name and namespace seem to be of any importance there. The Secret is passed down to the https://github.com/giantswarm/kubeconfig package, and from there to the Kubernetes upstream packages, which as far as I can tell, relies on the current context when set, and both of the aforementioned operators do it.

Now, I am not sure what to do with it. I believe nothing is the best option here, with maybe a small addition to the docs that this field does not matter. The reason being, the oldest work related to context name I managed to find is 4 years old, and was an introduction of kubeconfig in the Cluster Operator. Context-related work in other components is a bit younger, for it is usually reaches back for ~2 years. So, in conclusion, I think I can assume for at least 2 years this feature hasn't been working, yet the App Platform was fine. And since nobody complained on this, nobody really needs this feature, so I would be a little hesitant in fixing it. First, nobody seems to care, second I would be afraid of now breaking the App Platform for all the components seem to use anything but the right names, so I would probably fail after fixing this. I think it would be much better to mark [this App CR's field](https://github.com/giantswarm/apiextensions-application/blob/b6b97f19c3b179c034331fed096c0e4d69f228ad/api/v1alpha1/app_types.go#L229) as deprecated, and then update our docs accordingly letting users know then do not need to care anymore.
