### ISSUE TITLE
Deny-all network policy for CAPA

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2860]
After https://github.com/giantswarm/giantswarm/issues/27266, we found that the newly introduced deny-all policy, together with removal of cilium-app's `defaultPolicies.enabled=true` means some operators cannot reach the API server nodes anymore. Those operators have a `NetworkPolicy` with the correct CIDR range allowed, but Cilium has a known issue (https://github.com/cilium/cilium/issues/20550) which renders the allow rules ineffective. While the fix is not released and Cilium not upgraded on our side, we have to set `defaultPolicies.enabled=true` again in order to keep things working. We can expect the Cilium fix to be released quite soon.

We could also instrument all our apps with a `CiliumNetworkPolicy` allowing `toEntities: [ kube-apiserver ]`, but that's a lot of effort.

**Comment by T-Kukawka** [comment]
We will have to update cilium-app to get this feature, cc @giantswarm/team-turtles maybe if you have some time, if not we will try to make it

**Comment by Rotfuks** [comment]
Btw...we got another ticket just like that in our backlog that's currently being worked on by rocket: #2815  
So maybe you can check with @gawertm for cooperation on it here aswell :)

**Comment by gawertm** [comment]
are we talking about MC or WC deny all policies? Rocket is working to make this work as discussed in Kaas sync for panamax WCs. (because they are already very far with capvcd and a later migration would could hurt us). I would need to recall the exact approach, but I believe once we have it, it will be very easy for you to adopt the same for CAPA @T-Kukawka 
cc @jkremser

**Comment by AndiDog** [comment]
It's both MC and WC stuff. Any operator that uses `NetworkPolicy` to reach the k8s API, such as `metrics-server` which goes into all clusters.

**Comment by AndiDog** [comment]
The [fix](https://github.com/cilium/cilium/issues/20550#issuecomment-1748786958) is in release [cilium v1.15.0-pre1](https://github.com/cilium/cilium/releases/tag/v1.15.0-pre.1), not in a stable release yet. We should discuss whether we want to try for CAPA only, for instance.

**Comment by AndiDog** [comment]
@whites11 and me checked that apps belonging to default-apps-aws (= the most important ones that must work) can be adapted to include a `CiliumNetworkPolicy`. That's a quick win to get things working. Once that's done, we can introduce the deny-all policy (and remove `defaultPolicies.enabled` again).

**Comment by whites11** [comment]
After checking with Andreas, we believe the best way forward to finally fix this issue is:

- disable default cilium NPs in cilium app config in `cluster-aws` [PR](https://github.com/giantswarm/cluster-aws/pull/475)
- set `ciliumNetworkPolicy.enabled = true` to all relevant apps in `default-apps-aws`
- add back the deny all network policies as we have [in vintage](https://github.com/giantswarm/k8scloudconfig/blob/master/files/k8s-resource/network_policies.yaml)

This way vintage and capa will be aligned in terms of network policies and we don't need to wait for cilium 1.15
