### ISSUE TITLE
Investigate App Platform vs. Helm Releases

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2867]
### Motivation
As we learned in https://github.com/giantswarm/roadmap/issues/2773 we have two ways on how to wrap bundles already in place: Using the App Platform and using Helm Releases. We also have a proposed guidance for when to use App Platforms (for customer facing apps) and Helm Releases (for core kubernetes apps). Now we need to find a good guideline when to use helm releases and when to use apps. 

### Todo
- [ ] investigate the detailed difference between app platform and helm releases
- [ ] clearify with the other kaas teams and honeybadger what guideline we could set up here. 

### Outcome
- We have a good guidline proposal for when to use app platform and when helm releases that we are confident kaas and platform can understand and support.

**Comment by njuettner** [comment]
We did discuss App Platform vs. Helm Releases

The rough idea of Honeybadger will be:

- App CR will be used only to install HelmRelease via Flux, also to smoothen the migration to CAPI clusters
- Chart-Operator will be gone, since everything will be installed by Flux.
- Honeybadger will merge separate Flux for GiantSwarm and Customer into one Flux only per MC.  The reason why HelmReleases are currently not faster than our platform is due to running multiple Flux in our MC's. If that is fixed it should be faster to create cluster. Also they want to upgrade Flux to v2.

Honeybadger mentioned it will take a while (some months) to tackle it.

**Comment by Rotfuks** [comment]
We had the meeting and learned that we're recommending App Chart as a contract between App Owners and Honeybadger responsible for delivery of those apps to the clusters. Can be closed with this outcome.
