### ISSUE TITLE
Expand mc-bootstrap tests to validate installed apps

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2930]
Currently we only ensure that mc-bootstrap runs successfully but we have no further validation of what happens with the apps installed after.

Acceptance criteria:

- [x] Goal is not to change the MC and test it (like app testing, upgrades etc) but rather validate that it comes up successfully as it is.
- [x] The mechanism of validation should be as similar as possible to WC testing (ideally using the same tools as [clustertest framework](https://github.com/giantswarm/clustertest)).

Task:
- [x] Implement test framework that can deal with MCs
- [x] Consume framework from tekton pipeline

**Comment by AverageMarcus** [comment]
Ok, I've been able to think about this and have a rough idea what it might look like...

### Some considerations

1. This shouldn't be directly tied to the current `mc-bootstrap` setup as there is work being done to replace it with a CLI, instead this should be complementary and not rely on either the current or new implementation of mc-bootstrap
2. It should be possible to use these tests to validate production MCs as well as the ephemeral test MCs (likely with less tests run against prod)
3. The tests need to be runnable from both Tekton CI and from local dev laptops.

### Approach

* Create a new repo for the test suites (likely `managementcluster-test-suite` to align with existing)
* The test suite will follow the similar approach to `cluster-test-suites` and `apptest-framework` and be built on top of `clustertest`. I suspect that only a single test suite will exist though rather than the per-provider (+ variants) we have for WCs. There might be a separate upgrade tests but that's currently out of scope I think.
* The test suite should be packaged as a container image (like with WCs) so it can be called from Tekton easily 
* The test suite should expect a `E2E_KUBECONFIG` env var pointing at the MC to test (the MC must already have been created)
* The test cases should make use of [Spec Labels](https://onsi.github.io/ginkgo/#spec-labels) (or [Label Sets](https://onsi.github.io/ginkgo/#label-sets)) to indicate the following:
  * If a specific test is only applicable to a specific provider (hopefully theres not many of these cases)
  * If a test has side-effects (such as creating or deleting resources) that wouldn't be good to run against a production MC
  
  These labels will then be used to filter the tests that are run based on the MC that is being tested
* `mc-bootstrap` should be updated with a new Make target that triggers the test suite (from latest container image?) using the Kubeconfig of the created MC from the earlier step. 
* The new CLI should be updated to also include the ability to trigger these tests (I'm not sure what the current state of this CLI is so not 100% sure about this bit)
* The `mc-bootstrap` Tekton Pipeline should be updated with a new Task between the generate and cleanup that runs the new test suite.
* Team Tinkerers will likely need to be the CODEOWNERS of the repo but it should be treated like the other test suites and contributed by all teams (including the app teams)

**Comment by AverageMarcus** [comment]
Relevant from on-site discussion (taken from [Slack thread](https://gigantic.slack.com/archives/C07KQB3EPSN/p1726052634025519)):

To summarise:
We create a new `management-cluster-test-suites` that runs the cluster-wide “validation” / integration tests against an MC created by mc-bootstrap. The kubeconfig will be passed through from mc-bootstrap and just run as part of the current pipeline before the teardown task.
For individual app testing we have a pool of (let’s say) 10 ephemeral MCs pre-configured that we can make use for with app test suites. We then have automation that ensures at least 1 MC is “pre-warmed” at start of business day that the first run of app tests can use. When an app test is triggered we (in the background) launch the next MC in the pool so it’s ready for the next tests. Because we have a limited number of available MCs to use we’d need to use a queue in case there are more than 10 test ru

**Comment by AverageMarcus** [comment]
I'm going to consider this initial issue completed and close this.

There's still some extra work to do after this issue (add all providers, fix failing tests) but I'm going to create individual issues to track those.

@yulianedyalkova do we have an issue for individual app tests on MCs yet?

**Comment by AverageMarcus** [comment]
Test failures:
* https://github.com/giantswarm/giantswarm/issues/31818
* https://github.com/giantswarm/giantswarm/issues/31819

Enforce tests once above are resolved: https://github.com/giantswarm/giantswarm/issues/31820

**Comment by yulianedyalkova** [comment]
@AverageMarcus we do now - https://github.com/giantswarm/roadmap/issues/3708. I've already added our decisions in it.

**Comment by AverageMarcus** [comment]
✨ _Perfect!_ ✨

Thank you :)

**Comment by QuentinBisson** [comment]
Amazing work
