### ISSUE TITLE
teleport-operator with Machine ID (tbot)

### ISSUE THREAD

**Issue by vvondruska** [giantswarm/roadmap#2948]
Problem:
- Currently, teleport-operator is using a shared credential to access Teleport Cluster.

Motiviation:
- We want to use Machine ID (tbot) to use short-lived credential to access Teleport Cluster.

Here's high level overview of challenges associated with using Machine ID:
![Image](https://github.com/giantswarm/roadmap/assets/5674762/92e32ccf-9988-4c1d-8769-62dd7603b27e)

**Comment by tuladhar** [comment]
Demo: https://gigantic.slack.com/archives/C053JHJC99Q/p1699458462289799

**Comment by tuladhar** [comment]
Demo 2: https://gigantic.slack.com/archives/C053JHJC99Q/p1699538523935049

**Comment by tuladhar** [comment]
PR ready for review: 
- https://github.com/giantswarm/teleport-operator/pull/32

**Room for improvements:**
- Maybe, move the hashing stuff and time ago calculation to outside cluster_controller.go
- Move the teleport-operator secret to configmap, since, it doesn’t contain secrets anymore (as it doesn’t have identityFile anymore) which we are now getting dyamically from tbot.
  - Will need updating to test cases as well.
- Maybe, add more test cases.
