### ISSUE TITLE
Expose and document `MixedInstancesPolicy` setting

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2984]
In Vintage we are supporting setting similar instance types for Node Pools, that helps to scale them up when other instances are unavailable. We have to replicate this in CAPA clusters as well.

CAPA provides a [field](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c5a06683bf3ac602062f6fd0e450ae74aa1fd3af/exp/api/v1beta2/awsmachinepool_types.go#L74) MixedInstancesPolicy for MachinePools that does exactly that.

This value has to be exposed in the chart such that customers can set their favorable instance types.

- [ ] expose the value
- [ ] document the setup for customers with examples

**Comment by fiunchinho** [comment]
@T-Kukawka is it fine if this only works when not using spot instances? I think we want to rely on karpenter when using spot instances anyway. I ask because AWS complains when specifying spot instances and a `MixedInstancesPolicy`

```
InvalidQueryParameter: Incompatible launch template: You cannot use a launch template that is set to request Spot Instances (InstanceMarketOptions) when you configure an Auto Scaling group with a mixed instances policy. Add a different launch template to the group and try again.
```

When we first introduced `MixedInstancesPolicy` in `cluster-aws` we experienced the same issue, and we decided not to pass it when using Spot instances https://gigantic.slack.com/archives/C02HLSDH3DZ/p1694601240845049

**Comment by T-Kukawka** [comment]
to confirm from slack - we are doing this for on-demand only indeed, Spots are and will be handled by Karpenter
