### ISSUE TITLE
some renovate PRs are failing

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3016]
Some of the `renovate` PRs for dependency updates in our repositories are failing in CI: https://github.com/pulls/review-requested
We need to check logs in CircleCI, find out what's wrong and try to solve the issues so that dependencies can be up to date.

**Comment by OnurYilmazGit** [comment]
- giantswarm/athena fixed by updating  github.com/nats-io/nkeys to v0.4.6

**Comment by OnurYilmazGit** [comment]
- Successfully managed all Renovate pull requests (PRs). Successfully addressed issues in approximately six PRs, primarily involving the API and Teleport, and merged these into their respective main branches.

- Addressed major issues related to vulnerabilities and dependency conflicts.

- Encountered a specific issue with the API branch's Renovate PRs failing due to vulnerability concerns. Temporarily resolved this by adding certain packages to the 'nancyignore' file. This is a provisional measure for two weeks, until new, secure versions of these packages are released.

- Continuously monitoring for PR failures and addressing them as needed. Current status: all critical issues resolved.
