### ISSUE TITLE
Reduce docs image size form more than 900 MB

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3033]

**Comment by ljakimczuk** [comment]
I briefly checked that, and this size seems due to the size of page built by `hugo`:

```sh
> docker history gsoci.azurecr.io/giantswarm/docs

IMAGE                CREATED        CREATED BY                                                       SIZE         COMMENT
77415a24369b   3 days ago     COPY /public /usr/share/nginx/html # buildkit   907MB     buildkit.dockerfile.v0
...
```

It seems confirmed inside the container:

```sh
> du -sh /usr/share/nginx/html

900.8M	.
```

The biggest directory out there seems the `changes`:

```sh
> du -sh /usr/share/nginx/html/changes

822.5M	/usr/share/nginx/html/changes
```

The content of `changes/` directory seems to be a subject of automated updates according to [this list](https://github.com/giantswarm/docs/blob/main/scripts/aggregate-changelogs/config.yaml) of apps.

Looking at it seems like it contains some apps that are deprecated for example, so maybe we could reduce the size by removing entries for them.

**Comment by marians** [comment]
Thanks for the investigation!

Since changelogs account for 90% of the entire payload, I'll look into

1. Removing outdated projects
2. Removing releases beyond a threshold date
3. Compressing HTML using gzip

I thought we were doing (3) already, but it seems we're not.

**Comment by marians** [comment]
https://github.com/giantswarm/docs/pull/2040 brings the size down to ~160 MB
