### ISSUE TITLE
Image names produced by image-builder should include Flatcar version and channel

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3073]
Part of https://github.com/giantswarm/roadmap/issues/2978.

**Comment by JosephSalisbury** [comment]
hola @yulianedyalkova 

in sig arch @tuladhar brought up some frustration bigmac is having with updating the teleport binary that we're baking into the images (and someone in sig arch linked me this issue, so i'm randomly dropping in here hihihi)

could you have a chat with him, see whether there's anything we can do in tinkerers to make bigmac's life easier? i reckoned it was easier for the two of you to talk than for me to try and proxy badly :D

also, in sig arch we had some concern that it's currently possible to rebuild images and overwrite existing images, which can possibly lead to nodes updating - if that is a possibility, we need to ensure that images being built can't lead to nodes rolling in any way

happy to chat sometime if i've missed anything <3

also cc @AverageMarcus because we chatted a bit here, to close the loop. bam!

**Comment by AverageMarcus** [comment]
@JosephSalisbury Moved to its own issue here: https://github.com/giantswarm/giantswarm/issues/30530

**Comment by ericgraf** [comment]
Changes have been merged and new post has been put out.
