### ISSUE TITLE
Introduce app repo test configuration

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3268]
Each repo should have a way to configure:
* provider(s) to run tests against (single one, list, all)

The data from the configuration should be passed on and consumed by the pipelines.

**Comment by AverageMarcus** [comment]
It's currently possible to control the provider used by passing it along with the slash command ([example](https://github.com/giantswarm/ingress-nginx-app/pull/601#issuecomment-1997064066))

Multiple providers can be triggered by commenting multiple slash commands.

How important is it right now to have multiple provider support configured by default?

**Comment by AverageMarcus** [comment]
Decision:

* Align with how mc-bootstrap triggers multiple pipelines from a single slash command (we'll want to rename the Pipeline)
* The Github check name needs to be updated with the provider name so multiple can be added to a single commit
* The config file will contain a property that can have an array or provider contexts to test against (e.g. `capa`)
* If no property found in the config we should prob default to a provider (likely CAPA as we currently use that)

**Comment by AverageMarcus** [comment]
Completed! 
Example PR: https://github.com/giantswarm/ingress-nginx-app/pull/601

The `/run app-test-suites` command now runs a new pipeline that looks up what providers the app should be tested against and then triggers new pipelineruns for each provider. 
Each provider has its own GitHub check and generates its own comment on the PR. 

Individual provider pipelineruns can be re-triggered with something like `/run app-test-suites-single PROVIDER=capv`

The config struct in apptest-framework has been updated to also include the new property (but isn't used by anything).

Devctl has been update so that the config file that is generated has a default `providers` array containing just `capa` as a default. 

If the `providers` property isn't found in the config file then `capa` is used as a default.

The apptest-framework readme has been updated with details about the config.yaml properties.
