### ISSUE TITLE
Sales Enablement - Service Mesh

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#3288]
Overview of Service Mesh apps - marketing evaluation, not technical
e.g: with adidas removing Linkerd, Linkerd changing the release process

An example of Sales interaction where Service Mesh knowledge is required:
most prospects/customers use Istio, we would evaluate their use case and suggest to move to our Managed solution. We need to convince them that migration makes sense. They will want to hand over all the management of the app if they agree to migrate.

**Comment by snizhana-dynnyk** [comment]
Hi @weatherhog!
There is a request from our Sales team to provide them with more knowledge on Service Mesh solutions to be able to discuss such use cases with prospects and make suggestions. 
Since @giantswarm/team-cabbage has all the expertise,  can you prepare an overview of Service Mesh apps and have a short Q&A session?
And would it be possible to organize this before Kubecon?

**Comment by weatherhog** [comment]
What do you mean with an Overview of Service Mesh Apps? A comparison between all different Apps that are out there on the market? Or do you mean an overview over Service Mesh capabilities? 

The Question about if this is possible before Kubecon is related to the question above. If it is about capabilities then it is a yes, if it is about apps then it is a no - because then I would use Kubecon to scan the market.

**Comment by snizhana-dynnyk** [comment]
I also just checked the calendar, and before Kubecon, it is really tough. I also absolutely love the idea of using Kubecon to scan the market and share your findings in Sales Enablement! Then let’s do this, and I will schedule a call for the second week of April because many people will go to the Easter holidays after Kubecon 🙃

**Comment by snizhana-dynnyk** [comment]
scheduled on 11th of April, will also post an announcement in news-product
