### ISSUE TITLE
Implement best practices for `grafana-agent` app

### ISSUE THREAD

**Issue by marieroque** [giantswarm/roadmap#3341]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [ ] the app has properly set PDBs (as percentages)
- [ ] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [ ] the app runs with more than 1 replica by default (if it needs HA)
- [ ] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by hervenicol** [comment]
* Running more than 1 replica (HA setup) requires to externalize the Grafana database (from `sqlite` to `mysql` or `postgresql`). See [Set up Grafana for high availability](https://grafana.com/docs/grafana/latest/setup-grafana/set-up-for-high-availability/).
* horizontal scalability requires more than 1 replica
* PDBs require more than 1 replica

So the first step for this issue is to run grafana with a "real" database and HA.
It's not only a change of architecture, but also changes how we operate grafana: this will add persistence to custom-imported dashboards and datasources.

**Comment by Rotfuks** [comment]
This is not really feasible for us and will be closed out of scope for now. 

we are adressing any stability issues of the grafana agent app by improving the resource usage. Closing it for now.
