### ISSUE TITLE
Patch cilium values.yaml in the cilium-app repo

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#3348]
We want to experiment and try to patch values.yaml after running `vendir sync` in the app repo instead of having it changed in `cilium-upstream` repo.

This is because it's difficult to keep track of changes when switching to another minor branch of cilium (minor branches in cilium are not compatible). We should also in general keep the amount of custom changes in the `*-upstream` repos to minimum.

**Comment by ubergesundheit** [comment]
Since the upstream repo already has a Makefile for generating the values.yaml from a template, why not try to extend it to make yaml merging possible in the fork? I understand that this is not exactly what you want, but this would make sure the helm schema is always up to date since its also auto-generated in the fork.

The `main` branch of cilium/cilium used `yq` in said makefile. Maybe this can be also used for yaml merging there? (Maybe also worth contributing)

**Comment by kopiczko** [comment]
I'd like to have something universal. If we make it work with the cilium Makefile it won't work with other upstream repos.

**Comment by mcharriere** [comment]
Do we consider this `done`?

**Comment by kopiczko** [comment]
Yeah that done :)
