### ISSUE TITLE
Discussion: `zot` deployment modes

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3370]
Important info: `zot` will not become a critical component, in the sense that if it fails, all the clusters will still be able to fetch images directly from the upstream registry. Main goals for `zot` are to increase reliability and bootstrap times and (hopefully, hard to measure) lower the cost.

We can deploy `zot` for customer's and ours use in the following modes:

1. `zot` as a central service on an MC, used by the MC and all its WCs
- pros:
  - better cache hit ratio
  - better resources utilization
  - easier management (running, monitoring)
  - lower cost
- cons
  - can be potentially overloaded and become a problem to manage in a stable state

2. `zot` as a default app, running in each WC
- pros:
  - self-contained WCs
  - potentially easier to run, as instances will be smaller
- cons:
  - worse hit ratio
  - higher cost and resource usage (for sure in storage, might be CPU and mem as well)

We want to get started with a single zot on MC anyway (so 1. approach), but if we see any issues with running this instance, we're open to reconsider and make it a per-WC default app.

**Comment by LolloneS** [comment]
Thinking about big customers and the fact that we might/will want the cache to work for _their_ components as well in the long term for cost savings, SHA-matching, etc., I'd strongly suggest taking the following into account:
- multiple low environments running "ephemeral" nodes (spot instances) constantly pulling from the MC, hammering it
- multiple environments, including low ones, running a ton of stuff, which is all cached in a central place


As far as Lukasz's points are concerned:
- _operational load, where we have N services on N WCs instead of 1 on MC_
  - comment: N services might be "easy" to maintain whereas a single, huge service might be a PITA (think about prometheus now). Number of services is not the only metric here. Also, if the single big service hammers the MC, we are just moving the operational load elsewhere.
- _operational cost, same as above: N times disk, cpu and mem, for very little, if any, gain_
  - comment: meh. Especially if caching takes layers into account, it's not like storing our images is going to cost a lot. also, "N times" only holds for our components, whereas customers run different images in different environments on the same MC anyway.
- _much lower cache efficiency, or even efficiency, as all the images have to be fetched from upstream anyway for each and every cluster_
  - I can't foresee any cache efficacy if a single instance of zot needs to store images from $list-of-big-WCs-running-in-a-very-big-MC, to be honest

**Comment by vxav** [comment]
One of the main concerns of our hybrid architecture is to maintain operations in the on-prem WC in case of internet connectivity failure or a security event that would bring the customer to disconnect the on-prem WC. 

In which case, having a per-WC registry (not necessarily per-node caching) is a requirement as, otherwise, the WC nodes would no longer have access to the registry running in the MC. Which would negatively impact scaling and creation operations on nodes that haven't used that image before.

**Comment by kopiczko** [comment]
Copy of https://github.com/giantswarm/roadmap/issues/3369#issuecomment-2025348633

> I'm with @stone-z [here](https://gigantic.slack.com/archives/C01F7T2MNRL/p1711626907008769?thread_ts=1711625643.884949&cid=C01F7T2MNRL) about per-WC registries.
> 
> When it comes to storage:
> 
> * for daemonstats we pull all the images in all the nodes anyway so it's like one more node when it comes to storage
> * for images that are running only on some nodes - they probably won't be that useful (or reused) in other clusters anyway (e.g. when a different version of an image is used, or the app is not running in another cluster at all)
> * and there shouldn't be a lot of images in general per single WC, at least I think so, how much do we give for the docker volume? 50GB (and that includes empty-dir)?
> 
> Also when it comes to cost:
> 
> * traffic between on-prem and azure (or any public trafic) costs money
> * loadbalancers cost money (in local registry we could use a service)
> 
> When it comes to operational costs:
> 
> * yes, there is more registries to operate but:
> * there are no LBs
> * no ingresses
> * no connectivity issues between provides, networks etc.
> * smaller latency
> * no auth
> * no DDoS issues
> * maybe running dozen of smaller registries is more reliable than running a single big one
> * blast radius is smaller when per-WC registry goes down
> 
> Also, there a natural evolution path if per-WC registry solution is not enough which is moving to shared registry. But if it is enough, then it's way simpler. Also it will be easier to prove if it makes sense at all to go with shared registry given the complications.

**Comment by stone-z** [comment]
My thoughts have mostly been expressed in the thread and echoed here by others. To summarize, I'm in favor of a registry per-WC by default because I see it as the natural evolution of this problem, an inevitable need, and in fact a need we have already had for a while.
- it improves the resiliency of OCI operations (image + chart pulls, signature verification, reporting etc.) under network failure conditions
- it still reduces pulls on public image registries by orders of magnitude
- it reduces shared dependencies between clusters (credentials, DNS)
- as Pawel mentioned, it massively simplifies access and authentication and keeps the blast radius much smaller
- it doesn't need to run with five nines uptime in order to be very effective at mitigating public registry outages, improving pull performance, and supporting disconnected clusters

I'd go a step further and suggest the following as implementation considerations:
- the WC registry should be packaged in a way that we can easily run multiple of them. For example, one for us, and one or more for customers. Otherwise, we will inevitably have operations issues related to the size and scale of a single zot (when the disk gets full of 40GB customer images, for example).
- running WC zot is not mutually exclusive with pulling from MC-based registries or redundant public registries. `containerd` would support a failover strategy pulling first from WC zots and then from external registries. I'd argue we already need to reconfigure this failover for multiple public registries anyway, and suggest this effort be combined with any containerd work needed for WC zot
- others have mentioned using a per-node caching mechanism like [kube-fledged](https://github.com/senthilrch/kube-fledged) either instead of or in addition to the WC- or MC-scoped registry. I could imagine situations where selectively using that in tandem with a WC registry could be beneficial, but I don't see a need to do that by default now. That would only partially meet the known needs and have other downsides, like the storage required to pre-cache every image on every node (which we'd need to do to mitigate the network outage case without a WC registry)

**Comment by piontec** [comment]
Thanks for all the comments :)
We will start with a central, MC-located cache, mainly for the purpose of learning: we have zero operational experience with zot and we want to learn about its performance and stability. After running it for some time on test MCs, we will re-evaluate the deployment modes and all. Still, for in-cluster only, [spegel](https://github.com/spegel-org/spegel) might be a better choice.

Please keep in mind, that we're not ruling out running zot as WC app - this is already supported and zot can be deployed at will on WCs. We're now trying out if and how it runs and performs as a MC-level cache.

**Comment by weatherhog** [comment]
@piontec does this issue still need to be watched? is there a way forward or can it be closed?

**Comment by piontec** [comment]
No, we're good. We cover all the deployment mdoes and they are described in the docs.
