### ISSUE TITLE
Wire up tests on releases repo

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3477]
Part of https://github.com/giantswarm/roadmap/issues/3473.

As part of the [new releases flow](https://github.com/giantswarm/rfc/pull/96) we'll have to wire up tests on the releases repo. Flow should look like this:
- [ ] PR with new release gets created and tests get triggered on it
- [ ] Release name can be provided in the PR trigger, we will [later](https://github.com/giantswarm/roadmap/issues/3490) expand with dynamic logic
- [ ] Release CRD gets created on the MC
- [ ] We run `cluster-test-suite` against that release
- [ ] Upgrades are out of scope for this issue, will be handled [here](https://github.com/giantswarm/roadmap/issues/3489)

**Comment by AverageMarcus** [comment]
I have some questions I need clarified before work on this can be done.

1. How do we plan to detect what releases in a PR need testing? Can we assume that a PR that needs testing will always have a new (or changed) line in the `resources` array of the `${PROVIDER}/kustomization.yaml`? Is there ever a case where we'll create a PR that makes a change to an existing release and not adding a new one?

2. For each new provider release do we run all the test suites available for that provider in cluster-test-suites? E.g. for CAPA releases we would run ~5 WC tests.

3. Do we have any helper functions yet to parse a release from a `release.yaml` file? (If not a simple file read and `yaml.Unmarshal` should be enough I think). I need to think more about how the framework will handle this but I suspect we might need some functionality in the builder (or similar) to pull a specific release from a specific commit. Otherwise we need to handle passing files about in the pipeline workspace and have the framework support reading from local file which complicates things when running locally.

4. I suspect that we might have PRs with multiple releases in them (e.g. bumping the Kuberentes version for all providers at the same time) - would we want each release to have its own GitHub check or would a single one that reports the state of all be ok? Maybe we want one per provider? (Note: This decision has an impact on branch protection / pr-gatekeeper)

5. I assume we also want to be testing upgrades as part of this. Can I assume that the test should upgrade from the latest available release for that provider?

6. Is there anything special / different we need to be aware of with regards to multi-provider MCs? (e.g. CAPV-on-CAPZ)

/cc @giantswarm/team-turtles

**Comment by yulianedyalkova** [comment]
I was thinking that as a first iteration, it would make sense to keep things very simple and then build up on top of it. Which would mean:
* provide the release name to be tested in the PR trigger
* ideally upgrade should be tested from the release that would come right before the one provided in the target. The latest one might not work when we're working on patches for older releases, for example.

But also ping @nprokopic for thoughts.

**Comment by AverageMarcus** [comment]
> ideally upgrade should be tested from the release that would come right before the one provided in the target. The latest one might not work when we're working on patches for older releases, for example.

Ah, didn't think about that.

I feel like upgrades should be handled separately after we have standard tests in place so we don't overcomplicate things to begin with. Thoughts?

**Comment by yulianedyalkova** [comment]
> I feel like upgrades should be handled separately after we have standard tests in place so we don't overcomplicate things to begin with. Thoughts?

I completely agree, we can take care of it in a follow-up issue as it's not critical for getting things out now.

**Comment by AverageMarcus** [comment]
Can we split that out into its own issue then and refocus this one? :) Make sure we don't forget about it after.
