### ISSUE TITLE
Dynamically calculate which releases to run tests against

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3490]
As we now have [tests](https://github.com/giantswarm/roadmap/issues/3477) for the new releases framework, we not need to think about how to dynamically decide which releases to run tests against.

Some of the questions we need to consider are linked [here](https://github.com/giantswarm/roadmap/issues/3477#issuecomment-2159985426).

**Comment by AverageMarcus** [comment]
I've been trying to work out how to handle this in a Tekton Pipeline and currently struggling to come up with anything maintainable so I'm writing out my thoughts here to try and work though them... enjoy 🤣 

### Some assumptions
* A single PR could have multiple releases for different providers
* To begin with we only care about the `standard` test suite in each provider (for simplicity right now)

### Optional params

Ideally we want to support user-provided params on the trigger comment so I expect the following to be _optionally_ available for use:
* `TARGET_SUITES` - specifies the test suites from cluster-test-suites to run. This allows only re-running flaky suites if needed. This is already in use in our `/run cluster-test-suites` triggers.
* `TARGET_RELEASES` - specifies the Releases to run tests against. This can be comma separated to provide multiple and each release must exist in the PR. This allows for re-running a specific release if only changes to that release has been made since last running the tests.

If either of these aren't provided by the user we need to work them out automatically from the PR contents (see below).

If these are provided we need to check a few things:
* Do the `TARGET_RELEASES` exist in the PR?
* Is the combination of `TARGET_RELEASES` and `TARGET_SUITES` valid? E.g. are they both the same provider?

### Working out the suites and releases automatically

Working out the test suites to run based on the release should be relatively simple. Each release must be prefixed with the provider name which we then need to match up with the appropriate standard test suite. E.g. `aws-25.0.1` => `./capa/standard`. This mapping will need to be manually handled as the provider prefixes don't match the providers we use in the test suites.

Working out the releases to test against is a little more complicated. We will need to inspect the git commit and do a diff against the `main` branch to work out which releases are newly added, or changed, in the PR. We currently don't have anything similar to this in any of our Pipelines so would need some trial and error I suspect.

### Triggering the tests

Once we know both the releases and the test suites we need to pair them up based on the provider. 
Because of this we can't make use of a `matrix` in the Tekton Task as it would result in all possible combinations of test suite and release.

There are two ways that I can think of so far to handle this:
1. Have a task that produces an array result that contains the release and test suite as a concatenated string and then use this as the matrix param. This will ensure that our provider pairings are respected but it means we couldn't use the current `run-wc-e2e-tests` Task as it wouldn't know how to handle that concatenated string.
2. Use a similar approach to apptests where we launch a new PipelineRun for each provider. I'm still not really happy with this approach for app testing so reluctant to go down this path here too. This has a couple downsides - slower startup as we wait for more PipelineRuns to be created and ends up with multiple different check runs on the GitHub PR which each need a unique name (and makes things tricky with branch protection). 

---

So, I'm not really sure how to tackle this as I'm pretty sure anything I come up with is going to be nasty to maintain. 😞  I'd love to hear any ideas anyone else has.

**Comment by yulianedyalkova** [comment]
Already handled by https://github.com/giantswarm/roadmap/issues/3477.
