### ISSUE TITLE
irsa-operator fails to remove finalizer

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3618]
In my e2e test run, cluster deletion is failing in upgrade tests (seems inconsistent), and I tracked it down to irsa-operator failing to remove its finalizer from AWSCluster CR.

These is the error from irsa-operator:

```
2024-07-30T12:29:37Z	ERROR	Reconciler error	{"controller": "awscluster", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "AWSCluster", "AWSCluster": {"name":"t-tjupwewq9lhluvusov","namespace":"org-t-rgd8t8fdvqpzy4nfad"}, "namespace": "org-t-rgd8t8fdvqpzy4nfad", "name": "t-tjupwewq9lhluvusov", "reconcileID": "4d76889d-140f-4cda-8bc9-1f519610d060", "error": "ConfigMap \"t-tjupwewq9lhluvusov-cluster-values\" not found"}
```

Looks like that the deletion reconciliation fails as irsa-operator fails to find (I assume already deleted) cluster values ConfigMap.

As a consequence, leftover CRs are piling up in grizzly :see_no_evil:

Does irsa-operator need cluster values ConfigMap here? Can it just ignore if it is not there?

**Comment by iuriaranda** [comment]
I think I found the problem. On cluster deletion, the IRSA operator first removes the finalizers from the cluster values ConfigMap, and then from the `AWSCluster` CR ([here](https://github.com/giantswarm/irsa-operator/blob/master/controllers/capa_controller.go#L176-L184)). When removing the finalizers from `AWSCluster`, a race condition can occur, where another operator is also removing their finalizers at the same time, in such case the patch operation will fail. There's already a retry mechanism in place for such situations ([here](https://github.com/giantswarm/irsa-operator/blob/master/controllers/capa_controller.go#L248-L260)).

The problem is (I think) that, during the patching, the k8s client library panics instead of returning an error, so the retry mechanism never kicks in, so the finalizer never gets removed from `AWSCluster` on the first deletion reconciliation loop. Then subsequent reconciliations fail because the cluster values ConfigMap is already gone.

![Image](https://github.com/user-attachments/assets/334f127c-eac4-4590-82ef-2ff97234dbf2)
