### ISSUE TITLE
cert-exporter fails when there are not ready certificates

### ISSUE THREAD

**Issue by fiunchinho** [giantswarm/roadmap#3632]
When there are certificates that are not `Ready`, cert-exporter deployment fails with
```
{"caller":"github.com/giantswarm/cert-exporter/exporters/cr/exporter.go:93","error":{"kind":"unknown","annotation":"parsing time \"\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"\" as \"2006\"","stack":[{"file":"/root/project/exporters/cr/exporter.go","line":93}]},"time":"2024-08-12T10:17:32.213745+00:00"}
```

It's currently stuck on `CrashLoopBackOff` on `alligator` / `int02`.

**Comment by weseven** [comment]
From the go code in case of non ready certificates cert-exporter [should just log the error when parsing the not after and continue with the next certificate CR](https://github.com/giantswarm/cert-exporter/blob/50d911393f3fe7ff6569e938993031ddead162a6/exporters/cr/exporter.go#L94).

I think it's crashing because it's being OOM killed:

```
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 13 Aug 2024 10:40:14 +0200
      Finished:     Tue, 13 Aug 2024 10:41:07 +0200
    Ready:          False
    Restart Count:  17
    Limits:
      cpu:     150m
      memory:  50Mi
    Requests:
      cpu:        50m
      memory:     50Mi
```

This should be fixed by adding a VPA resource (tracking issue https://github.com/giantswarm/roadmap/issues/3625).

**Comment by fiunchinho** [comment]
Thanks for taking a look! I'll close this one then.
