### ISSUE TITLE
New releases not being distributed on all installations

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3663]
Acceptance criteria:

- [ ] Investigate why new releases are not being distributed on all installations

**Comment by njuettner** [comment]
[Slack Thread](https://gigantic.slack.com/archives/C07KSM2E51A/p1727173252660979) which explains why it's currently not applying releases in MC's

**Comment by AverageMarcus** [comment]
Related threads:
* https://gigantic.slack.com/archives/C07KSM2E51A/p1727788515429729
* https://gigantic.slack.com/archives/CLPMFRVU6/p1727788936150309?thread_ts=1727788228.473829&cid=CLPMFRVU6

Couple things going on here:
* At least on `enigma` some / all of the Release CRs were applied manually and are thus missing the required labels so the App is failing to install or upgrade. We need to manually clean this up but we should create an alert for this first so that we can catch this in advance in the future.
* We are using the git commit sha as the App version instead of actual semver versions. Because of this, the "latest" version is being incorrectly worked out as the highest alphabetical sha version instead of the latest published. This means if a sha is alphabetically lower than the previous release's sha it wont be deployed to ANY MC.

**Comment by Gacko** [comment]
I just manually bumped the `release-capa` app version in the `capa-app-collection` so the latest CAPA Release CRs get deployed to CAPA MCs: https://github.com/giantswarm/capa-app-collection/commit/260deaa286bc18f4badd31094a2d15de148143b5

**Comment by Gacko** [comment]
Releases are now deployed via GitOps on CAPI MCs. See the following PRs for details:

- https://github.com/giantswarm/management-cluster-bases/pull/162: This deploys the `releases` repository as `GitRepository` to every cluster and adds a generic way to easily include provider releases in MC configurations.
- https://github.com/giantswarm/management-cluster-bases/pull/163: This PR by default includes one MC's provider releases in its configuration. This Kustomization is already being included everywhere in `<provider>-management-clusters`, so it simply deploys the provider specific releases Kustomization to every MC.
- https://github.com/giantswarm/management-cluster-bases/pull/164: Here I enabled pruning for the `collection` Kustomization as a preparation for removing the `releases-<provider>` app from app collections.
- https://github.com/giantswarm/releases/pull/1473: Here I add the `helm.sh/resource-policy: keep` annotation to Release CRs so they stay around once the `releases-<provider>` app gets removed from an MC.
- Afterwards I removed the `releases-<provider>` apps from app collections:
  - https://github.com/giantswarm/capa-app-collection/commit/f7c9f34e78a14b9332205d22edfa1b8d555b7f23
  - https://github.com/giantswarm/capz-app-collection/commit/d248e83433c3f5d9961a1f466e4fd7a1f6bc0099
  - https://github.com/giantswarm/vsphere-app-collection/commit/96f72ca4de8836417335af117ca48fe28fe18320
- At this point the `releases-<provider>` apps got removed from MCs. I already checked them and verified Release CRs are still around and managed by Flux. ✅ 

Now we only need to remove the `helm.sh/resource-policy: keep` annotation again with this PR https://github.com/giantswarm/releases/pull/1477 and enable pruning for the `releases-<provider>` Kustomizations so archived Release CRs are getting removed from MCs in this PR https://github.com/giantswarm/management-cluster-bases/pull/165.

**Comment by Gacko** [comment]
And with this little PR I also updated `mc-bootstrap`: https://github.com/giantswarm/mc-bootstrap/pull/1055
