### ISSUE TITLE
Add analytics-panel plugin to g8s-grafana

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#378]
Towards https://github.com/giantswarm/roadmap/issues/364

We need to add the analytics-panel plugin to g8s-grafana so we can then add it to all the dashboards, so we can get analytics data

**Comment by mig4** [comment]
For ref, there's an issue upstream re plugin not getting loaded correctly on Grafana 8 - https://github.com/MacroPower/macropower-analytics-panel/issues/21 - this is due to how it's built which causes it to end up with executable permission on files which the new Grafana doesn't like.

Release [2.0.1](https://github.com/MacroPower/macropower-analytics-panel/releases/tag/v2.0.1) fixes this by switching to official release workflow. This only landed a couple of hours ago and it's not in [marketplace](https://grafana.com/grafana/plugins/macropower-analytics-panel/) yet.

**Comment by mig4** [comment]
Waiting for: https://github.com/grafana/grafana-plugin-repository/pull/1021

**Comment by mig4** [comment]
Release [2.1.0](https://github.com/MacroPower/macropower-analytics-panel/releases/tag/v2.1.0) also includes the fix for using relative paths 🎉 

And so now waiting for Grafana folks to merge it into Marketplace here: https://github.com/grafana/grafana-plugin-repository/pull/1028

In the meantime I've re-built the [2.1.0](https://github.com/MacroPower/macropower-analytics-panel/releases/tag/v2.1.0) release and pushed it to https://gitlab.com/mig4/macropower-analytics-panel-gs/-/packages

My PR to add the plugin to our Grafana setup is here: https://github.com/giantswarm/g8s-grafana/pull/326 (currently includes a hack to use the above build, which can be changed back once that version [lands in Marketplace](https://github.com/grafana/grafana-plugin-repository/pull/1028)).

**Comment by mig4** [comment]
For reference, I use something like this to build and publish the plugin (fish syntax):

``` sh
# this can be done in a container started from the `node` image with `zip` package installed

yarn install --frozen-lockfile
yarn build
set plugin_id (jq -r '.id' dist/plugin.json)
set plugin_version (jq -r '.info.version' dist/plugin.json)
mv dist $plugin_id
zip -r $plugin_id-$plugin_version.zip $plugin_id

# and to publish

curl --header 'PRIVATE-TOKEN: <GITLAB-ACCESS-TOKEN>' --upload-file $plugin_id-$plugin_version.zip "https://gitlab.com/api/v4/projects/28621844/packages/generic/$plugin_id/$plugin_version/$plugin_id-$plugin_version.zip"
```

(for publishing I just created an empty GitLab project and use its [generic package repositories](https://docs.gitlab.com/ee/user/packages/generic_packages/index.html) feature)
