### ISSUE TITLE
CAPVCD failure zones / node placement

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3798]
We might have to look into this at some point.

Context: https://gigantic.slack.com/archives/CE92C4BST/p1727765125494859

**Comment by gawertm** [comment]
placement policy exists in VCD machine template.
also the maintainers starting to work on zones, but not sure where they left off when leaving the project.
We should evaluate if we can use some feature like that or how much effort it would be to finish this feature

**Comment by gawertm** [comment]
xavier's comments https://gigantic.slack.com/archives/CE92C4BST/p1727770415141169?thread_ts=1727765125.494859&cid=CE92C4BST

**Comment by anvddriesch** [comment]
`placementPolicy` is supported in the chart and can be used.
Xavier will ask neoedge to create a placement policy for us that we can reference for testing.

**Comment by vxav** [comment]
Loris got back to me and said they can't really do it because it would mess a bit with the sheduling of the workloads since the environment is shared.

I'll ask the customer tomorrow during the sync if they can create the DRS groups, rules and placement policy to test it with `Glasgow` or `Tamarin`.

**Comment by vxav** [comment]
I created an issue in the customer board with details on how this works
https://github.com/giantswarm/telekom-panamax/issues/337

**Comment by vxav** [comment]
The feature is there. We can close in favor of ☝
