### ISSUE TITLE
Create AWS cluster in the organization's namespace by default

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#387]
Create AWS cluster in the organization's namespace by default.

## Tasks
- [ ] make a change in admission controller to create cluster resources in org namespaces by default
- [ ] update docs with a release version where org namespace is used by default https://docs.giantswarm.io/general/organizations/#namespace-use

**Comment by anvddriesch** [comment]
What happened so far:
- Tried mutating the namespace inside a webhook. This does not work due to the namespace on the request and the namespace on the resource having to match
- Tried mutating the webhook on the client side. (kubectl-gs in this case) this obviously works fine. However, we have more clients and customers create their templates in various ways

What we want to do next:
- Talk to customers/stakeholders to find out what all templating pipelines look like and come up with a good solution to implement
- Later when we have the templating, we still want to add validation to the admission-controller.

**Comment by anvddriesch** [comment]
There are open PRs in `api`, `kubectl-gs` and the `aws-admission-controller` to support creation of new clusters in the org-namespace by default. We have discussed about this with firecracker today.

- The cluster creation in org-namespace by default will apply to clusters from `v16.0.0` to ensure a smooth transition.
- If a cluster in the default namespace is upgraded to `v16.0.0` and higher, it should not create problems. Additional resources (e.g nodepools) for this cluster should be created in the default namespace as well.
- We need to validate that resources for one cluster are created in the same namespace
- Because kubectl-gs has no way of knowing whether a nodepool in `v17.0.0` is created for a cluster in default namespace, we need an additional flag to explicitly set the namespace in case applying the default one fails due to different namespaces of cluster and nodepool.

**Comment by anvddriesch** [comment]
All changes have been merged. 

What remains to be done before v16.0.0 release:
- Release `kubectl-gs`, `api` and `aws-admission-controller`. (No rush. for now it won't change anything as v16.0.0 is not out. But it should be done before we test it.

Upon v16.0.0 release:
- Change the standard namespace in `kubectl-gs` to the org-namespace
- Update docs

**Comment by calvix** [comment]
should we close this?

**Comment by anvddriesch** [comment]
Yeah this is done with 16! :)
