### ISSUE TITLE
Turn the 'hello-world' app into a real catalog app in playground catalog.

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#419]
This will allow to make an in-happa tutorial about how to lookup, install and manage app in happa's "getting started" guide

**Comment by marians** [comment]
Thanks Łukasz!

This is about providing an app to deploy https://github.com/giantswarm/helloworld.

We should make sure to not break our Getting Started guide in the process, e. g. by turning that repository into an app.

**Comment by marians** [comment]
@ubergesundheit @piontec I see that https://github.com/giantswarm/hello-world-app is configured to be published via the "Giant Swarm" catalog. I question whether that makes sense, since we are not planning to support it (or are we?). "Playground" would be the better choice, to not dilute our user's understanding of the catalogs meanings.

**Comment by ubergesundheit** [comment]
I think I changed the catalog to "Giant Swarm" in order to have this usable in some kind of tutorial for the app platform. If it is also possible for customers to install this from the playground, I can easily change this.

Regarding support.. There is not much to support, its a simple Deployment + Ingress which serves the Giant Swarm hello world web page.

**Comment by JosephSalisbury** [comment]
@ubergesundheit is this done? can we close?

**Comment by marians** [comment]
Is one of these two outdated? If yes, it would be nice if it could be removed to avoid confusion.

![image](https://user-images.githubusercontent.com/273727/135996527-23b3b1b8-8f5a-4d57-8902-ac8ee0bc861e.png)

**Comment by ubergesundheit** [comment]
The one one in playground is the old one. I'll push something to the catalog to remove it.

**Comment by ubergesundheit** [comment]
https://github.com/giantswarm/hello-world-app/releases/tag/v0.1.0 for reference
