### ISSUE TITLE
Why are we getting paged by Prometheus not running and not Atlas?

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#636]
Why are we getting paged by Prometheus not running and not Atlas?

**Comment by whites11** [comment]
The only occourence of a prometheus-related alert that I found is this: https://giantswarm.app.opsgenie.com/alert/detail/028729a6-dff7-4465-ad86-5a2e8599ffef-1639478710664/details

It's about the prometheus-meta-operator deployment not being satisfied.

Defined here: https://github.com/giantswarm/prometheus-rules/blob/49737a3872a1e9488dad718b83846593969a12dc/helm/prometheus-rules/templates/alerting-rules/deployment.management-cluster.rules.yml#L71

I am not super happy about being paged by this, but I guess most of the time if the deployment is unsatisfied is because of some cluster problem so I can live with this.
