### ISSUE TITLE
Web UI shows app as switching to new version when it's actually the same version

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#647]
Found in c68pn on gollum.

![image](https://user-images.githubusercontent.com/273727/145967598-049da556-4862-4b03-a9f2-5228202aa379.png)

The docs-app has `.spec.version: v2.2.269` and `.status.version: 2.2.269`. The only difference is the `v` prefix.

I'm guessing that we show the "Switching to..." text because the version strings are not an exact match.

**Comment by marians** [comment]
@ljakimczuk @rossf7 I am seeing this for the first time now after the switch to Flux.

I am wondering what is the right way to fix this. The fact that we have the `v` prefix in one but not the other field looks a bit sketchy to me.

However if it must be that way, we can change the matching in the web UI to work either way, so that the web UI does not display the "Switching to..." string.

**Comment by marians** [comment]
Another problem here is that the version selection drop-down menu does not match the `v2.2.269` key with the v prefix.

![image](https://user-images.githubusercontent.com/273727/145969340-fc431e3d-0ca1-4b61-aab1-d5de94958bc0.png)

The cause is the same as above.

**Comment by marians** [comment]
One additional note: If a user selects an item from the version selection (e. g. to roll back to a previous version) it will set the `.spec.version` field to a version number without `v` prefix.

**Comment by ljakimczuk** [comment]
Hey @marians , find my comments below.

> I am wondering what is the right way to fix this. The fact that we have the v prefix in one but not the other field looks a bit sketchy to me.

The `v` prefix is not set in other fields, because this solution seemed the most reasonable and the easiest one to implement. If we propagated it downstream to other fields, then probably we would need to patch more tools and/or CRs, so that all of them support both notations, namely the `vX.Y.Z` and the `X.Y.Z`. It seemed more reasonable to just extend the interface a little bit allowing users to set the `vX.Y.Z` version, but then trimming the `v` before propagating it downstream. Would it be possible to trim this prefix in Happa before processing the version in any way?

> One additional note: If a user selects an item from the version selection (e. g. to roll back to a previous version) it will set the .spec.version field to a version number without v prefix.

This problem concerns more Flux vs Happa topic, than just the `v` prefix versions. In general, if we have some apps deployed with Flux, and thus managed by GitOps processes, then any changes made through the UI will get reverted. We set the `giantswarm.io/managed-by: flux` on the apps managed by Flux, so Happa could skip them or display in read-only mode I guess?

**Comment by marians** [comment]
Trimming any v prefix on a version in happa is easy. I just hope that we are not creating a new problem though that.

> This problem concerns more Flux vs Happa topic, than just the `v` prefix versions. In general, if we have some apps deployed with Flux, and thus managed by GitOps processes, then any changes made through the UI will get reverted. We set the `giantswarm.io/managed-by: flux` on the apps managed by Flux, so Happa could skip them or display in read-only mode I guess?

That's issue https://github.com/giantswarm/roadmap/issues/624

**Comment by PrashantR31** [comment]
:+1:  Thanks
