### ISSUE TITLE
Investigate why we are getting paged for WorkloadClusterContainerIsRestartingTooFrequentlyAWS.

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#655]
Investigate why we are getting paged for WorkloadClusterContainerIsRestartingTooFrequentlyAWS.

**Comment by whites11** [comment]
A lil bit of data https://docs.google.com/spreadsheets/d/1gB3Z-U6nH6SfrBjG3sdIJCY4N2uGXhgREum9OlfB3i4/edit#gid=0

**Comment by whites11** [comment]
There are mainly 3 apps that page because they are restarting too often:

- kiam
- cluster-autoscaler
- aws-cni

Considering they are all upstream apps, my suggestion is:

1. ensure we have a legacy release with the latest version of all the above apps
2. try to  push customers to upgrade their clusters.

For point 1 I already ensured we have the latest versions available and we will use it in the next release
For point 2 we should get in touch with the customers. The installations that are paging the most are anteater and viking.
