### ISSUE TITLE
Enable EBS CSI volume snapshots

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#668]
**Is your feature request related to a problem? Please describe.**

A customer has tried to make use of Volume Snapshot in AWS (k8s `1.21`) and it did not work as expected. The customer wanted to do a migration of volumes from EBS `gp2` to `gp3` ([blog post related](https://aws.amazon.com/es/blogs/containers/migrating-amazon-eks-clusters-from-gp2-to-gp3-ebs-volumes/)).

**Describe the solution you'd like**

There were missing [role permissions](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/f5b404b9c85a168745ad24d0ab3b5d8ad1072724/deploy/kubernetes/base/clusterrole-snapshotter.yaml) on the first try. For some reason, the snapshot controller running in the ebs csi driver did not make the work and we need to deploy [external-snapshotter](https://github.com/kubernetes-csi/external-snapshotter) along with the main driver.

Finally, we need to make sure the EBS Volume Snapshot permissions are used in the IAM role of the controller or add them to the [instance role](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/example-iam-policy.json). 

**Describe alternatives you've considered**

**Additional context**

**Comment by njuettner** [comment]
`aws-ebs-csi-driver-app >= 2.7.1` should be fine (no changes needed), RBAC permissions are the same as upstream but as Fernando mentioned we need to fix the IAM policy on the worker nodes since the snapshot-controller will be deployed on the worker nodes (snapshot-controller is optional).

snapshot-controller can be enabled by adding user values for aws-ebs-csi-driver-app: `enableVolumeSnapshot: true`

IAM policy will be fixed with release `16.3.0`
