### ISSUE TITLE
Move RBAC-bootstrap to the Giant Swarm catalog

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#743]
### Description

The `RBAC app` is currently in the Playground catalog and used by 1 customer.  We need to make sure it meets the quality standards before moving it to the Giant Swarm catalog and announcing to other customers.

### TODO

- [x] Add public documentation
- [x] Make sure quality standards have been met (the is a doc describing this)

**Comment by PrashantR31** [comment]
Hi @pipo02mix , we would like to know if there is anything pending from your part as we would like to push this app to the GS Catalog now i.e add Monitoring, Docs ..etc.

**Comment by pipo02mix** [comment]
I have been added the docs to the README and the chart is compliant with [basic level](https://intranet.giantswarm.io/docs/dev-and-releng/app-developer-processes/application-quality-bars/#basic-level).

**Comment by PrashantR31** [comment]
1. Monitoring; When App fails @giantswarm/team-rainbow will be paged.
2. knowledge sharing session so that we know the app better and support. 
3. What has been done and what can be done when it fails, so as to support it "professionally"
@PrashantR31 schedule a meeting + @anvddriesch doing a precheck

**Comment by anvddriesch** [comment]
![Screenshot from 2022-02-24 19-15-49](https://user-images.githubusercontent.com/56017655/155505803-14225ff4-8c78-4a59-a0ff-8ea58d5d0d5c.png)
