### ISSUE TITLE
Support cinder csi volume snapshots.

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#752]
### User Story 
- As a giantswarm openstack user I want the cinder CSI volume snapshopt plugin to be deployed in my clusters so that I can use it to create backups.

#### Tasks

- [x] extend cloud-provider-openstack app to deploy snapshot controller ( enable by default) 

See: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/features.md#volume-snapshots

**Comment by ericgraf** [comment]
The snapshotController is already present. It simply needs to be enabled in the values.yaml file.
https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/cinder-csi-plugin/values.yaml#L86

**Comment by cornelius-keller** [comment]
Can we enable it by default and close this ticket?

**Comment by cornelius-keller** [comment]
Notes from planning:
- enable it for beta
- make sure it is documented for ga

**Comment by bavarianbidi** [comment]
i assume we have to extend `cluster-api-cleaner-openstack` to delete existing snapshots first bevore we delete volumes [`volumes.go`](https://github.com/giantswarm/cluster-api-cleaner-openstack/blob/main/pkg/cleaner/volumes.go)

**Comment by erkanerol** [comment]
@bavarianbidi I just tested the cleaner operator. It works without any change thanks to this option https://github.com/giantswarm/cluster-api-cleaner-openstack/blob/main/pkg/cleaner/volumes.go#L57

**Comment by erkanerol** [comment]
To be able to create snapshots, we need to install these two:

- CRDs from https://github.com/kubernetes-csi/external-snapshotter (volumesnapshotclasses, volumesnapshotcontents and volumesnapshots)
- External snaphotter https://github.com/kubernetes-csi/external-snapshotter/tree/041cd4674149a30cdc53a98a3fd7d343b9fd90eb/deploy/kubernetes/snapshot-controller


Then the user needs to create a `volumesnapshotclasses` at first then `volumesnapshots` per snapshot. Since we create storageclasses by default, I though that we need to create a default volumesnapshotclasses as well. 

This [PR](https://github.com/giantswarm/cloud-provider-openstack-app/pull/34) adds all of them to `cloud-provider-openstack-app`. However, the CRDs and controllers are not OpenStack specific. We can move them into a new app. In that case, the question is where default volumesnapshotclasse must stand. We cannot put it into a platform agnostic app. When we keep it in `cloud-provider-openstack-app`,  the new app will be a dependency of `cloud-provider-openstack-app`.  Not sure about it as well.

**Comment by erkanerol** [comment]
Update: We decided to introduce a provider-agnostic app for external-snapshotter. Here is the repo: https://github.com/giantswarm/csi-external-snapshotter-app/pull/1

**Comment by erkanerol** [comment]
https://github.com/giantswarm/default-apps-openstack/pull/47 Snapshot feature was merged to the main branch. It will be in the next version (after 0.5.0) of default-apps-openstack. I keeping this issue open since we are discussing whether we should add webhooks as well or not. See https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes/webhook-example
