### ISSUE TITLE
Improve help for kubectl gs template cluster

### ISSUE THREAD

**Issue by ghost** [giantswarm/roadmap#756]
kubectl-gs `template cluster` command should provide explanation and examples in the usage (`--help`). Has nothing currently.

**Comment by PrashantR31** [comment]
Hello @giantswarm/team-honeybadger and @giantswarm/team-rocket would you have something to contribute, please ?

**Comment by kubasobon** [comment]
Flags are descriptive enough for me, but an example would be great. One I could almost copy-paste.

**Comment by PrashantR31** [comment]
Hii @tfussell , would you have some example to add here please.

**Comment by tfussell** [comment]
We will have public docs available once https://github.com/giantswarm/giantswarm/issues/20821 is merged. I can copy the example command into the `--help` output for now.

That said, there was a concern about having too much provider-specific information there. My best idea to deal with that was to move `kubectl gs template cluster --provider <provider>` into a subcommand like `kubectl gs template cluster <provider>` so that the help text can only show flags relevant to the given provider. What does everyone think about that?

**Comment by cornelius-keller** [comment]
closing as team rocket and customers are not using kubectl-gs, documentation also seems sufficient for other teams now.
