### ISSUE TITLE
`opsctl list installations` should show whether the REST API is available or not.

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#775]
Towards https://github.com/giantswarm/giantswarm/issues/20455 roadmap item, spec found in the same issue.

**Comment by PrashantR31** [comment]
We are will be using `opsctl login` which will add more information on the installation and therefore we lower the priority on this ticket for now and revisit it afterwards.

**Comment by marians** [comment]
As we discussed in the team, this isn't highly relevant any more, now that `opsctl login` decides which mechanism to use.

Also, as long as we don't have a declarative way of specifying whether the REST API should be deployed, we would have to iterate over all installations in order to find out whether it is running. We can't do that with `list installations`, as it would make the command unusably slow.
