### ISSUE TITLE
Support scheduling cluster upgrades via the web UI

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#822]
Cluster upgrades can be scheduled in advance using `kubectl gs` ([docs](https://docs.giantswarm.io/ui-api/kubectl-gs/update-cluster/)), and we previously implemented a feature to display this scheduled upgrade time in `happa` ([related issue](https://github.com/giantswarm/happa/pull/2919)). It would also be nice if we could support scheduling upgrades from the web UI.

**Comment by puja108** [comment]
@alex-dabija can you give the input or context needed here

**Comment by alex-dabija** [comment]
The current implementation doesn't follow the [RFC](https://github.com/giantswarm/rfc/tree/main/automatic-cluster-upgrades) we have for cluster upgrades. It was done as the simplest possible implementation in order to not manually trigger cluster upgrades outside business hours.

I think we should decide if the current implementation is fine or if we want to implement the solution described in the RFC. More work would be needed if we change the UI now to use the current implementation.

**Comment by weatherhog** [comment]
closing
