### ISSUE TITLE
Falco not having enough priority and paging Phoenix

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#867]
Phoenix gets paged several times a day because `falco-app` can't be scheduled in the MC nodes.

There are a few things to say:

- there is no reason why phoenix should get paged for this. The cluster is 100% healthy. Thus as soon as team security has an oncall rotation we ask you to take over this alert.
- if falco strictly has to be running in all nodes, then let's raise its `priorityClass`

**Comment by stone-z** [comment]
The SIG discussed. Because the pods can't schedule, this is more a symptom of the MCs being generally out of resources and not a problem with falco. But we definitely want to make it nicer to oncallers.

Action items:
- Zach will bump the priorityclass of falco
- Some changes to node pool scaling are rolling out soon. We suspect it might help because prometheus [has](https://github.com/giantswarm/giantswarm/issues/12799) a [history](https://github.com/giantswarm/giantswarm/issues/14389) of [forcing](https://github.com/giantswarm/giantswarm/issues/14076) other [pods](https://github.com/giantswarm/giantswarm/issues/14640) off of nodes, often because it gets stuck on the only remaining node in an availability zone. The new behavior would make the scheduler aware of the need for more resources in a given AZ, so we will see if helps :crossed_fingers: 
  - If not, we may need to increase node sizes or revisit https://github.com/giantswarm/giantswarm/issues/14269

**Comment by stone-z** [comment]
Released priority class for Falco in v0.3.1 https://github.com/giantswarm/falco-app/pull/88

**Comment by stone-z** [comment]
Closing this as the quick fix has been released. If the problem persists or moves to a different component, we'll have to discuss increasing node sizes or revisiting our prometheus sharding
