### ISSUE TITLE
Research: Can we easily use circleci to generate compatibility tests

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#96]
## References
* Halo Apps Compatibility Testing Discussion [notes](https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#)

Research: can we easily use circleci to generate “platform version vs all supported apps versions” and “application version vs all supported platform releases” test scenarios and start a sub-test for each of them.

Configuration that solves that task for circleci or other proposed CI/CD system.

**Comment by cokiengchiara** [comment]
@yasn77 pls update this ticket w your findings and recommended next steps

**Comment by yasn77** [comment]
Current issues that I know about CircleCI that will make achieving our objectives more difficult:

CircleCI doesn't behave well with Kind -> https://gigantic.slack.com/archives/CUTGJ4NKA/p1586002606006800?thread_ts=1585328953.000100&cid=CUTGJ4NKA

Looks like CircleCI now supports build/test Matrix -> https://discuss.circleci.com/t/rfc-matrix-jobs-syntax/34468/13

However, it's still pretty new and not sure how well it work with our platform testing.

I think it might be worth investigating Guthub actions... Actions have supported Matrix (i think) since the beginning and there is already pretty decent support for testing in kind (https://github.com/marketplace/actions/kind-kubernetes-in-docker-action)

**Comment by cokiengchiara** [comment]
Closing this issue as the research is done. Transferred research findings here https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#heading=h.bz4in2qb8z6k
