### ISSUE TITLE
Private DNS + ACME

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#961]
Can we also use private DNS? This way no internal infrastructure would leak to the outside. 

 * [ ] Let's encrypt with private DNS?
 * [ ] Do we manage an internal zone ourselves?
 * [ ] How do we propagate internal DNS of our customers to our machines?

**Comment by alex-dabija** [comment]
We would prefer to use a public hosted zone because of the complications of propagating internal DNS of our customers to our machines.

There's no simple solution for this that I'm aware of and it does require doing DNS updates in 2 steps:
- update the private hosted zone on Route53 (A record);
- update a Giant Swarm private DNS server (A record);

We would also have to deal with doing the update from the customer's infrastructure to ours.

An alternative would be to forward DNS requests to the customer's DNS server through the VPN we are going to have in place. The issue here is that we have a single VPN and we need to ensure that specific queries for a domain end up to the correct customer's DNS server.

**Comment by alex-dabija** [comment]
We deployed two MCs (`thunder` & `thor`) configured with private DNS and a private ACME endpoint.

At the moment it's not possible to use Let's Encrypt with private DNS because the domain validation is only done over public DNS (you need to show that you own the domain). A mix of public and private DNS would be needed. We decided to not support such a configuration.
